// Writes docs/COMPONENTS.md (0.77.0) from the editor's own component tables:
// what each component is for (componentHelp.ts), its fields and defaults
// (CommandInterpreter's defaultComponent) with their labels and help
// (PropertyMetadata.ts), grouped like the Add component list. Run with
// `npx tsx tools/docs/gen_components.ts` from apps/editor; `--check` fails
// when the file is out of date.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defaultComponent } from "../../apps/editor/src/authoring/CommandInterpreter";
import { componentDescription, componentGroups, componentLabel, propertyMetadata } from "../../apps/editor/src/editor/PropertyMetadata";

const out = fileURLToPath(new URL("../../docs/COMPONENTS.md", import.meta.url));
const lines: string[] = [
  "# Components",
  "",
  "<!-- Generated by tools/docs/gen_components.ts from the editor's component tables. Don't edit. -->",
  "",
  "Every component the editor's **Add component** list offers, grouped the same way, with each field's default. The same descriptions appear as tooltips in the inspector. Scripts: see [SCRIPT_API.md](SCRIPT_API.md).",
  "",
];
const show = (v: unknown): string => {
  if (typeof v === "string") return v.includes("\n") ? `${JSON.stringify(v.split("\n")[0]).slice(0, 40)}…` : JSON.stringify(v.length > 60 ? v.slice(0, 60) + "…" : v);
  if (v && typeof v === "object") return Object.entries(v as Record<string, unknown>).map(([k, x]) => `${k}=${show(x)}`).join(" ");
  return String(v);
};
const flatten = (record: Record<string, unknown>, prefix = ""): Array<[string, unknown]> =>
  Object.entries(record).flatMap(([k, v]) => (v && typeof v === "object" && !Array.isArray(v) && Object.keys(v).every((x) => ["x", "y", "z"].includes(x)) ? [[prefix + k, v] as [string, unknown]] : v && typeof v === "object" && !Array.isArray(v) ? flatten(v as Record<string, unknown>, prefix + k + ".") : [[prefix + k, v] as [string, unknown]]));
for (const group of componentGroups) {
  lines.push(`## ${group.label}`, "");
  for (const type of group.types) {
    const label = componentLabel(type);
    lines.push(`### ${label}${label !== type ? ` (\`${type}\`)` : ""}`, "");
    const about = componentDescription(type);
    if (about) lines.push(about, "");
    let value: Record<string, unknown> = {};
    try {
      value = defaultComponent(type as never) as unknown as Record<string, unknown>;
    } catch {}
    const fields = flatten(value);
    if (fields.length) {
      lines.push("| Field | Default | Notes |", "|---|---|---|");
      for (const [path, v] of fields) {
        const meta = propertyMetadata(type, path);
        const notes = [meta.label && meta.label !== path ? meta.label : "", meta.help ?? "", meta.options ? `one of ${meta.options.map((o) => o.label).join(", ")}` : ""].filter(Boolean).join(". ").replace(/\|/g, "\\|");
        lines.push(`| \`${path}\` | ${show(v).replace(/\|/g, "\\|")} | ${notes} |`);
      }
      lines.push("");
    }
  }
}
const text = lines.join("\n");
let current = "";
try {
  current = readFileSync(out, "utf8");
} catch {}
if (current !== text) {
  if (process.argv.includes("--check")) {
    console.error("docs/COMPONENTS.md is out of date: run npx tsx tools/docs/gen_components.ts");
    process.exit(1);
  }
  writeFileSync(out, text);
  console.log("wrote docs/COMPONENTS.md");
}
