// The Lua scripting API (0.77.0), described once. `node
// tools/script_api/gen.mjs` writes from it:
//   source/engine/script/api_prelude.hpp  -- the named helpers below, as Lua
//   docs/scripting/engine_api.lua         -- a LuaLS stub for autocomplete
//   docs/SCRIPT_API.md                    -- the reference
//   apps/editor/src/editor/scriptApi.ts   -- the editor's API panel
// Built-in functions (C++) are documented here by signature; the named
// helpers wrap the older string protocols (space.call(op, ...) and
// host.send(kind, text)), which keep working.

// [table, name, signature, description]
export const builtins = [
  ["world", "find", "(name: string): integer?", "The id of the first entity with this name."],
  ["world", "name", "(id: integer): string?", "An entity's name."],
  ["world", "alive", "(id: integer): boolean", "False once the entity is destroyed."],
  ["world", "position", "(id: integer): number?, number?, number?", "Where the entity is."],
  ["world", "set_position", "(id: integer, x: number, y: number, z: number)", "Moves the entity."],
  ["world", "velocity", "(id: integer): number?, number?, number?", "Its velocity (m/s)."],
  ["world", "set_velocity", "(id: integer, x: number, y: number, z: number)", "Sets its velocity."],
  ["world", "spawn", "(prefab: string, x: number, y: number, z: number): integer?", "A new instance of a prefab; returns its id."],
  ["world", "destroy", "(id: integer)", "Removes the entity."],
  ["world", "health", "(id: integer): number?, number?", "Current and maximum health."],
  ["world", "damage", "(id: integer, amount: number)", "Hurts the entity (on_damaged, then on_death at 0)."],
  ["world", "heal", "(id: integer, amount: number)", "Restores health up to its maximum."],
  ["world", "give_ammo", "(id: integer, rounds: integer, slot?: integer)", "Adds reserve rounds to its weapon."],
  ["world", "raycast", "(ox, oy, oz, dx, dy, dz, max: number, mask?: integer): table?", "The first hit along a ray: {id, x, y, z, nx, ny, nz, distance}."],
  ["world", "overlap", "(x, y, z, radius: number, mask?: integer): integer[]", "Entities with colliders inside a sphere."],
  ["world", "send", "(id: integer, name: string, value?: any)", "Calls the entity's on_message(name, value, sender)."],
  ["world", "path", "(x, y, z, tx, ty, tz: number): table[]?", "Waypoints {x, y, z} around obstacles, or nil when unreachable."],
  ["world", "set_clock", "(hours: number): number", "The scene clock that Routines follow."],
  ["host", "send", "(kind: string, text: string)", "A raw message to the host (the named helpers below send these for you)."],
  ["physics", "add_force", "(id: integer, x: number, y: number, z: number)", "A force for this tick."],
  ["physics", "add_impulse", "(id: integer, x: number, y: number, z: number)", "An instant change of momentum."],
  ["sound", "play", "(name: string)", "Plays a sound from the catalog."],
  ["sound", "play_at", "(name: string, x: number, y: number, z: number, volume?: number)", "Plays a sound in the world."],
  ["sound", "volume", "(bus: string, level: number)", "Sets a mixer bus volume 0-1 (master, sfx, music, ambient, ui)."],
  ["ui", "set_text", "(name: string, text: string)", "Changes a UI element's text."],
  ["ui", "set_value", "(name: string, value: number)", "Sets a Bar, Slider or Toggle (0-1)."],
  ["ui", "set_visible", "(name: string, visible: boolean)", "Shows or hides a UI element."],
  ["ui", "marker", "(name: string, x: number, y: number, z: number, label?: string)", "An on-screen waypoint at a world position, pinned to the screen edge when off screen."],
  ["ui", "clear_marker", "(id: string)", "Removes a marker."],
  ["game", "pause", "()", "Pauses play."],
  ["game", "resume", "()", "Resumes play."],
  ["anim", "set", "(name: string, value: any)", "Sets an Animator parameter."],
  ["anim", "trigger", "(name: string)", "Fires an Animator trigger."],
  ["camera", "shake", "(intensity?: number, seconds?: number)", "Shakes the game camera (defaults 0.3, 0.4 s)."],
  ["vehicle", "state", "(id: integer): number, number, integer, number, number, boolean, boolean, number, number", "speed, forward, gear, rpm, nitro, drifting, boosting, yaw, slip."],
  ["vehicle", "set_nitro", "(id: integer, amount: number)", "Refills the nitro tank."],
  ["vehicle", "reset", "(id: integer, x: number, y: number, z: number, yaw: number)", "Puts the car back on its wheels at a place."],
  ["vehicle", "freeze", "(id: integer, frozen: boolean)", "Holds the car in place (countdowns)."],
  ["vehicle", "set_route", "(id: integer, route: string, loop?: boolean)", "An AI driver's route: 'x,z x,z ...'."],
  ["vehicle", "set_target", "(id: integer, target: integer)", "Who an AI driver pursues."],
  ["vehicle", "set_mode", "(id: integer, mode: string)", "Race, Pursuit, Traffic or Off."],
  ["vehicle", "set_speed_scale", "(id: integer, scale: number)", "Slows or speeds an AI driver."],
  ["space", "state", "(): table?", "The ship and frame: altitude, speed, fuel, hull, landed, frame, site, ..."],
  ["space", "events", "(): string[]", "touchdown, liftoff, soi:<body>, frame:<body>, site:<name>, reframe, ... since the last call."],
  ["space", "set_warp", "(factor: number)", "Time warp."],
  ["space", "set_assist", "(mode: string)", "manual, stabilized, prograde, retrograde or target."],
  ["space", "set_target", "(body: string)", "The navigation target."],
  ["space", "refuel", "(amount: number)", "Adds fuel."],
  ["space", "set_fuel", "(amount: number)", "Sets the fuel."],
  ["space", "tune", "(field: string, value: number)", "Changes a ship spec value (upgrades)."],
  ["space", "spec", "(): table", "{thrust, lift, fuel, hull, heat, rcs}"],
  ["space", "repair", "(amount: number)", "Repairs the hull."],
  ["space", "board", "()", "Puts the walker in the ship."],
  ["space", "exit", "()", "Steps out of the ship."],
  ["space", "set_controls", "(enabled: boolean)", "Lets the player fly (off for menus and cut-scenes)."],
  ["space", "place_landed", "(body: string, latitude: number, longitude: number, heading?: number)", "Sets the ship down at a place."],
  ["space", "place_orbit", "(body: string, altitude: number)", "Puts the ship in a circular orbit."],
  ["space", "body", "(name: string): table?", "{radius, gravity, atmosphere, distance, altitude}"],
  ["space", "call", "(op: string, text?: string, ...: number): table?", "The generic call the named helpers use."],
  ["particles", "burst", "(count: integer)", "A burst from this entity's emitter."],
  ["particles", "set_emitting", "(on: boolean)", "Starts or stops this entity's emitter."],
  ["melee", "perform", "(move: string): boolean", "Starts a move of this fighter's Melee list by name (when it can act)."],
  ["melee", "state", "(): string, integer, number, number, number", "Mode (idle, move, block, stun, airborne, down, getup, dead), combo, energy, energy max, guard 0-1."],
  ["melee", "move", "(): string", "The move playing, or \"\"."],
  ["melee", "set_energy", "(amount: number)", "Sets its energy (specials spend it)."],
  ["melee", "lock", "(id?: integer)", "Locks onto a target; no argument releases."],
  ["melee", "target", "(): integer?", "Who it faces and fights."],
  ["melee", "set_ai", "(on: boolean, aggression?: number, skill?: number)", "Hands the fighter to (or takes it from) its melee brain."],
  ["melee", "unlock", "(move: string): number?", "Makes a move marked locked usable; 1 when the move exists."],
  ["melee", "stagger", "(): number, number", "Its poise bar 0-1, and 1 while it's Broken."],
  ["weapon", "fire", "(dx?: number, dy?: number, dz?: number)", "Fires the current weapon (optionally along a direction)."],
  ["weapon", "reload", "()", "Reloads."],
  ["weapon", "select", "(slot: integer)", "Switches weapon."],
  ["weapon", "ammo", "(): integer, integer", "Rounds in the magazine and in reserve."],
  ["weapon", "give_ammo", "(rounds: integer, slot?: integer)", "Adds reserve rounds."],
  ["input", "down", "(key: string): boolean", "A key held this tick, by its code (KeyW, Space, Enter) or its lowercase name (w, enter)."],
  ["input", "pressed", "(key: string): boolean", "A key pressed this tick."],
  ["input", "action", "(name: string): number", "An action's value (axes -1..1, buttons 0/1)."],
  ["input", "action_down", "(name: string): boolean", "An action held."],
  ["input", "action_pressed", "(name: string): boolean", "An action pressed this tick."],
  ["input", "action_released", "(name: string): boolean", "An action released this tick."],
  ["input", "mouse", "(): number, number", "The mouse position in the viewport."],
  ["input", "mouse_down", "(button: integer): boolean", "A mouse button held."],
  ["input", "mouse_pressed", "(button: integer): boolean", "A mouse button pressed this tick."],
  ["input", "wheel", "(): number", "Scroll this tick."],
  ["input", "pad_down", "(button: string): boolean", "A gamepad button held."],
  ["input", "pad_pressed", "(button: string): boolean", "A gamepad button pressed this tick."],
  ["input", "pad_axis", "(axis: string): number", "A gamepad stick axis."],
  ["input", "pad_connected", "(): boolean", "A gamepad is connected."],
  ["input", "lock_mouse", "(locked: boolean)", "Captures the mouse for looking around."],
  ["save", "set", "(key: string, value: string)", "Stores a value that survives reloads."],
  ["save", "get", "(key: string): string?", "Reads a stored value."],
];

// Named helpers (0.77.0): [table, name, params, lua body, description].
// Params are "name: type" in order; the body may use them by name.
export const helpers = [
  ["space", "set_hull", "value: number", 'return space.call("hull", "", value)', "Sets the hull exactly (loading a save)."],
  ["space", "set_time", "seconds: number", 'return space.call("time", "", seconds)', "Sets the system clock: where every planet is."],
  ["space", "settle", "", 'return space.call("settle")', "Puts everyone with a Routine at the stop the clock says."],
  ["space", "reveal", "body: string", 'return space.call("reveal", body)', "Shows a hidden body."],
  ["space", "bodies", "", 'local r = space.call("bodies") return r and r.text or ""', "Every visible body, one per line: name and parent."],
  ["space", "plan", "body: string", 'local r = space.call("plan", body) if not r then return nil end return {distance = r[1], closing_speed = r[2], delta_v = r[3], fuel = r[4], status = r[5]}', "A route plan to a body: distance, delta-v and the fuel it needs."],
  ["space", "autopilot", "on: boolean", 'return space.call("autopilot", "", on and 1 or 0)', "Engages or releases the autopilot toward the target."],
  ["space", "use_reserve", "", 'return space.call("reserve")', "Releases the emergency fuel reserve (once, below 35%)."],
  ["space", "repair_part", "part: string, amount: number", 'local r = space.call("part", part, amount) return r and r[1]', "Repairs (+) or damages (-) engine, rcs, gear or scanner; returns its condition."],
  ["space", "set_wind", "x: number, y: number, z: number", 'return space.call("wind", "", x, y, z)', "Wind on the ship and walker (m/s, site frame)."],
  ["space", "allow_boarding", "allowed: boolean", 'return space.call("board_key", "", allowed and 1 or 0)', "Whether E boards the ship."],
  ["world", "wildlife_state", "name: string", 'local r = space.call("wildlife", name) return r and r[1] or -1', "0 calm, 1 wary, 2 fleeing, -1 not an animal."],
  ["hud", "announce", "text: string", 'host.send("announce", text)', "Reads a line aloud for screen readers and shows it briefly."],
  ["hud", "cue", "name: string", 'host.send("cue", name)', "Plays an interface sound cue."],
  ["hud", "waypoint", "id: string, body: string, latitude: number, longitude: number, label: string", 'host.send("waypoint", table.concat({id, body, latitude, longitude, label or ""}, "|"))', "A waypoint at a place on a planet."],
  ["hud", "clear_waypoint", "id: string", 'host.send("waypoint_clear", id)', "Removes a waypoint."],
  ["hud", "map", "mode: string", 'host.send("map", mode)', "off, system, surface or toggle."],
  ["hud", "minimap", "shown: boolean", 'host.send("minimap", shown and "1" or "0")', "Shows or hides the minimap."],
  ["hud", "open_settings", "", 'host.send("settings", "")', "Opens the player settings panel."],
  ["hud", "visor", "helmet: boolean, integrity: number, frost: number, heat: number", 'host.send("visor", string.format("%d %.2f %.2f %.2f", helmet and 1 or 0, integrity, frost, heat))', "The helmet visor: on or off, integrity 0-1 (cracks below), frost and heat shimmer 0-1."],
  ["hud", "suit_light", "mode: string", 'host.send("suitlight", mode)', "auto, on or off."],
  ["hud", "system", "title: string, body: string", 'host.send("system", title .. "|" .. (body or ""))', "Shows a Ledger system window (title, body lines split by \\n); replaces the open one."],
  ["hud", "system_close", "", 'host.send("system", "")', "Closes the Ledger system window."],
  ["hud", "panels", "spec: string", 'host.send("panels", spec)', "Plays a comic-panel cutscene: one shot per line, \"x y z > tx ty tz | caption | sfx | seconds\". Space or Enter skips."],
  ["hud", "boss", "name: string, title: string", 'host.send("boss", (name or "") .. "|" .. (title or ""))', "A boss bar (health and stagger) for the named entity; an empty name hides it."],
  ["audio", "music", "mood: string", 'host.send("music", mood)', "off, title, explore, night, flight, space, signal or tension."],
  ["audio", "ambience", "layer: string, level: number", 'host.send("audio", string.format("%s %.2f", layer, level))', "An ambience layer's level 0-1: wind, rain, settlement, wildlife or signal."],
  ["fx", "weather", "rain: number, fog: number, wind_x: number, wind_z: number", 'host.send("weather", string.format("%.2f %.2f %.1f %.1f", rain, fog, wind_x, wind_z))', "Weather: rain and fog 0-1, wind in m/s."],
  ["fx", "dust", "color: string, density: number", 'host.send("dust", color .. " " .. density)', "Dust kicked up on landing: a #rrggbb colour and 0-1 density."],
  ["fx", "soft_ground", "soft: boolean", 'host.send("soft", soft and "1" or "0")', "Whether footprints show."],
  ["scanner", "tune", "range: number, time: number, condition: number", 'host.send("scanner", range .. " " .. time .. " " .. condition)', "Scanner range, scan time and condition multipliers."],
  ["scanner", "sky_key", "key: string", 'host.send("sky_scan", key)', "What scanning the sky identifies."],
  ["scanner", "catalogued", "id: string", 'host.send("catalogued", id)', "Marks a scan id as already known."],
  ["scanner", "prospect", "label: string, range: number, keys: string", 'host.send("prospect", label .. "|" .. range .. "|" .. keys)', "Highlights scatter of these species keys (comma-separated); empty label stops."],
];

export const callbacks = [
  ["on_start", "()", "Once, when play starts."],
  ["on_tick", "(dt: number)", "Every tick (1/60 s)."],
  ["on_ui", "(name: string, value: any)", "A UI element was used, or the host sent an event."],
  ["on_message", "(name: string, value: any, sender: integer)", "Another script called world.send."],
  ["on_damaged", "(amount: number, attacker: integer?)", "This entity was hurt."],
  ["on_death", "(attacker: integer?)", "Health reached 0."],
  ["on_kill", "(victim: integer)", "This entity defeated another."],
  ["on_melee_hit", "(target: integer, move: string, damage: number, outcome: string)", "This fighter's blow met someone: hit, blocked, parried, dodged or guard_break."],
  ["on_collision_enter", "(other: integer)", "Started touching (also _stay, _exit)."],
  ["on_trigger_enter", "(other: integer)", "Something entered this trigger (also _stay, _exit)."],
  ["on_anim_state", "(state: string)", "The Animator entered a state."],
  ["on_anim_event", "(name: string)", "An Animator event fired."],
  ["after", "(seconds: number, fn: function): integer", "Calls fn once later; cancel(handle) stops it."],
  ["every", "(seconds: number, fn: function): integer", "Calls fn repeatedly."],
  ["start", "(fn: function)", "Runs fn as a coroutine that can wait(seconds)."],
];
