// Generates the scripting API files from tools/script_api/api.mjs (see its
// header). `--check` fails when any is out of date.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { builtins, callbacks, helpers } from "./api.mjs";

const root = fileURLToPath(new URL("../../", import.meta.url));
const generated = "Generated by tools/script_api/gen.mjs from tools/script_api/api.mjs. Don't edit.";
const params = (p) => (p ? p.split(",").map((x) => x.trim().split(":")[0].trim()) : []);
const helperTables = [...new Set(helpers.map(([t]) => t))];
const builtinTables = [...new Set(builtins.map(([t]) => t))];

// Lua: tables the helpers add to that aren't built in, then the helpers.
const lua = [
  `-- ${generated}`,
  ...helperTables.filter((t) => !builtinTables.includes(t)).map((t) => `${t} = ${t} or {}`),
  ...helpers.map(([t, name, p, body]) => `function ${t}.${name}(${params(p).join(", ")}) ${body} end`),
].join("\n");
const prelude = `// ${generated}\n// The named scripting helpers (0.77.0), run after the core prelude.\n#pragma once\n\nnamespace engine::script {\ninline constexpr const char *api_prelude = R"lua(\n${lua}\n)lua";\n} // namespace engine::script\n`;

// LuaLS stub.
const luaType = (t) => t.trim().replace(/\binteger\b/g, "integer");
const stubFn = (table, name, sig, doc) => {
  const m = sig.match(/^\((.*?)\)(?::\s*(.*))?$/);
  const args = m && m[1] ? m[1].split(/,(?![^(]*\))/).map((a) => a.trim()).filter(Boolean) : [];
  const lines = [`--- ${doc}`];
  const names = [];
  for (const a of args) {
    if (a === "...: number") {
      lines.push("---@param ... number");
      names.push("...");
      continue;
    }
    const [n, t = "any"] = a.split(":").map((x) => x.trim());
    const optional = n.endsWith("?");
    const clean = n.replace("?", "");
    // "ox, oy, oz, dx, dy, dz, max: number" style groups share the type.
    lines.push(`---@param ${clean}${optional ? "?" : ""} ${luaType(t)}`);
    names.push(clean);
  }
  if (m && m[2]) lines.push(`---@return ${m[2]}`);
  lines.push(`function ${table ? table + "." : ""}${name}(${names.join(", ")}) end`);
  return lines.join("\n");
};
const allTables = [...new Set([...builtinTables, ...helperTables])];
const stub = [
  "---@meta",
  `-- ${generated}`,
  "-- Put this file in your editor's Lua workspace (LuaLS) for autocomplete.",
  "",
  ...allTables.map((t) => `${t} = {}`),
  "",
  ...builtins.map(([t, n, sig, doc]) => stubFn(t, n, sig, doc)),
  ...helpers.map(([t, n, p, , doc]) => stubFn(t, n, `(${p})`, doc)),
  ...callbacks.map(([n, sig, doc]) => stubFn("", n, sig, doc)),
  "",
].join("\n\n");

// Markdown reference.
const md = [
  "# Script API",
  "",
  `<!-- ${generated} -->`,
  "",
  "Scripts are Lua 5.4, one per entity (the Script component). These are the callbacks the engine calls, the built-in tables, and the named helpers. An autocomplete stub for LuaLS is in [scripting/engine_api.lua](scripting/engine_api.lua); the editor's Script card has the same list under **API**.",
  "",
  "## Callbacks and timers",
  "",
  "| Function | When |",
  "|---|---|",
  ...callbacks.map(([n, sig, doc]) => `| \`${n}${sig}\` | ${doc} |`),
  "",
  ...allTables.flatMap((t) => [
    `## ${t}`,
    "",
    "| Function | What it does |",
    "|---|---|",
    ...builtins.filter(([bt]) => bt === t).map(([, n, sig, doc]) => `| \`${t}.${n}${sig}\` | ${doc} |`),
    ...helpers.filter(([ht]) => ht === t).map(([, n, p, , doc]) => `| \`${t}.${n}(${p})\` | ${doc} |`),
    "",
  ]),
].join("\n");

// The editor's list.
const entries = [
  ...callbacks.map(([n, sig, doc]) => ({ name: n, signature: `${n}${sig}`, doc, group: "callbacks" })),
  ...builtins.map(([t, n, sig, doc]) => ({ name: `${t}.${n}`, signature: `${t}.${n}${sig}`, doc, group: t })),
  ...helpers.map(([t, n, p, , doc]) => ({ name: `${t}.${n}`, signature: `${t}.${n}(${p})`, doc, group: t })),
];
const ts = `// ${generated}\nexport interface ScriptApiEntry {\n  name: string;\n  signature: string;\n  doc: string;\n  group: string;\n}\n\nexport const scriptApi: ScriptApiEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

const outputs = {
  "source/engine/script/api_prelude.hpp": prelude,
  "docs/scripting/engine_api.lua": stub,
  "docs/SCRIPT_API.md": md + "\n",
  "apps/editor/src/editor/scriptApi.ts": ts,
};
let stale = false;
for (const [path, text] of Object.entries(outputs)) {
  let current = "";
  try {
    current = readFileSync(root + path, "utf8");
  } catch {}
  if (current === text) continue;
  if (process.argv.includes("--check")) {
    console.error(`${path} is out of date: run node tools/script_api/gen.mjs`);
    stale = true;
  } else {
    writeFileSync(root + path, text);
    console.log(`wrote ${path}`);
  }
}
process.exit(stale ? 1 : 0);
