// Generated by tools/bridge/gen_fields.mjs from tools/bridge/fields.mjs. Don't edit.
#pragma once

enum class SpaceField : int {
    piloting = 0, // 1 while the player flies the ship
    ship_x = 1, // ship position in the site frame
    ship_y = 2,
    ship_z = 3,
    attitude_x = 4, // ship attitude quaternion in the site frame
    attitude_y = 5,
    attitude_z = 6,
    attitude_w = 7,
    altitude = 8, // metres above the reference body's surface
    speed = 9, // speed relative to the reference body (m/s)
    vertical_speed = 10,
    ground_speed = 11,
    throttle = 12, // 0..1
    fuel = 13, // 0..1 of the tank
    hull = 14, // 0..1
    heat = 15,
    air_density = 16,
    warp = 17, // time warp factor
    assist = 18, // 0 manual, 1 stabilized, 2 prograde, 3 retrograde, 4 target
    landed = 19,
    periapsis = 20,
    apoapsis = 21,
    orbit_closed = 22,
    reference_body = 23, // body index, -1 the star
    g_force = 24,
    engine_on = 25,
    belly_thrust = 26,
    system_time = 27, // seconds
    destroyed = 28,
    target_body = 29,
    target_distance = 30, // to the target's surface (m)
    site_distance = 31, // from the site origin (m)
    orbit_period = 32,
    eccentricity = 33,
    reference_radius = 34,
    has_space_system = 35,
    body_count = 36,
    away = 37, // 1 when the frame follows the ship or walker away from the authored site
    frame_generation = 38, // changes whenever the frame moves
    frame_body = 39,
    active_site = 40, // -1 home, -2 the wilds, else the Site number
    autopilot = 41,
    engine_condition = 42,
    rcs_condition = 43,
    gear_condition = 44,
    scanner_condition = 45,
    wind_speed = 46,
    ground_slope = 47, // degrees under the ship
    land_sink = 48, // the gear's limits: sink m/s
    land_slope = 49, // slope degrees
    land_drift = 50, // drift m/s
    water_below = 51,
    reframe_shift_x = 52, // the walker's shift in the latest on-foot re-anchor
    reframe_shift_y = 53,
    reframe_shift_z = 54,
    frame_latitude = 55, // degrees, body-fixed
    frame_longitude = 56,
    reframe_yaw = 57, // the turn about the vertical in that re-anchor (radians)
};

enum class EntityField : int {
    x = 0, // position
    y = 1,
    z = 2,
    health = 3, // current / max, -1 without Health
    heading_yaw = 4, // radians
    ai_state = 5, // AIState order (Idle, Walking, ...), -1 without an AI
};
