---@meta

-- Generated by tools/script_api/gen.mjs from tools/script_api/api.mjs. Don't edit.

-- Put this file in your editor's Lua workspace (LuaLS) for autocomplete.



world = {}

host = {}

physics = {}

sound = {}

ui = {}

game = {}

anim = {}

camera = {}

vehicle = {}

space = {}

particles = {}

melee = {}

weapon = {}

input = {}

save = {}

hud = {}

audio = {}

fx = {}

scanner = {}



--- The id of the first entity with this name.
---@param name string
---@return integer?
function world.find(name) end

--- An entity's name.
---@param id integer
---@return string?
function world.name(id) end

--- False once the entity is destroyed.
---@param id integer
---@return boolean
function world.alive(id) end

--- Where the entity is.
---@param id integer
---@return number?, number?, number?
function world.position(id) end

--- Moves the entity.
---@param id integer
---@param x number
---@param y number
---@param z number
function world.set_position(id, x, y, z) end

--- Its velocity (m/s).
---@param id integer
---@return number?, number?, number?
function world.velocity(id) end

--- Sets its velocity.
---@param id integer
---@param x number
---@param y number
---@param z number
function world.set_velocity(id, x, y, z) end

--- A new instance of a prefab; returns its id.
---@param prefab string
---@param x number
---@param y number
---@param z number
---@return integer?
function world.spawn(prefab, x, y, z) end

--- Removes the entity.
---@param id integer
function world.destroy(id) end

--- Current and maximum health.
---@param id integer
---@return number?, number?
function world.health(id) end

--- Hurts the entity (on_damaged, then on_death at 0).
---@param id integer
---@param amount number
function world.damage(id, amount) end

--- Restores health up to its maximum.
---@param id integer
---@param amount number
function world.heal(id, amount) end

--- Adds reserve rounds to its weapon.
---@param id integer
---@param rounds integer
---@param slot? integer
function world.give_ammo(id, rounds, slot) end

--- The first hit along a ray: {id, x, y, z, nx, ny, nz, distance}.
---@param ox any
---@param oy any
---@param oz any
---@param dx any
---@param dy any
---@param dz any
---@param max number
---@param mask? integer
---@return table?
function world.raycast(ox, oy, oz, dx, dy, dz, max, mask) end

--- Entities with colliders inside a sphere.
---@param x any
---@param y any
---@param z any
---@param radius number
---@param mask? integer
---@return integer[]
function world.overlap(x, y, z, radius, mask) end

--- Calls the entity's on_message(name, value, sender).
---@param id integer
---@param name string
---@param value? any
function world.send(id, name, value) end

--- Waypoints {x, y, z} around obstacles, or nil when unreachable.
---@param x any
---@param y any
---@param z any
---@param tx any
---@param ty any
---@param tz number
---@return table[]?
function world.path(x, y, z, tx, ty, tz) end

--- The scene clock that Routines follow.
---@param hours number
---@return number
function world.set_clock(hours) end

--- A raw message to the host (the named helpers below send these for you).
---@param kind string
---@param text string
function host.send(kind, text) end

--- A force for this tick.
---@param id integer
---@param x number
---@param y number
---@param z number
function physics.add_force(id, x, y, z) end

--- An instant change of momentum.
---@param id integer
---@param x number
---@param y number
---@param z number
function physics.add_impulse(id, x, y, z) end

--- Plays a sound from the catalog.
---@param name string
function sound.play(name) end

--- Plays a sound in the world.
---@param name string
---@param x number
---@param y number
---@param z number
---@param volume? number
function sound.play_at(name, x, y, z, volume) end

--- Sets a mixer bus volume 0-1 (master, sfx, music, ambient, ui).
---@param bus string
---@param level number
function sound.volume(bus, level) end

--- Changes a UI element's text.
---@param name string
---@param text string
function ui.set_text(name, text) end

--- Sets a Bar, Slider or Toggle (0-1).
---@param name string
---@param value number
function ui.set_value(name, value) end

--- Shows or hides a UI element.
---@param name string
---@param visible boolean
function ui.set_visible(name, visible) end

--- An on-screen waypoint at a world position, pinned to the screen edge when off screen.
---@param name string
---@param x number
---@param y number
---@param z number
---@param label? string
function ui.marker(name, x, y, z, label) end

--- Removes a marker.
---@param id string
function ui.clear_marker(id) end

--- Pauses play.
function game.pause() end

--- Resumes play.
function game.resume() end

--- Sets an Animator parameter.
---@param name string
---@param value any
function anim.set(name, value) end

--- Fires an Animator trigger.
---@param name string
function anim.trigger(name) end

--- Shakes the game camera (defaults 0.3, 0.4 s).
---@param intensity? number
---@param seconds? number
function camera.shake(intensity, seconds) end

--- speed, forward, gear, rpm, nitro, drifting, boosting, yaw, slip.
---@param id integer
---@return number, number, integer, number, number, boolean, boolean, number, number
function vehicle.state(id) end

--- Refills the nitro tank.
---@param id integer
---@param amount number
function vehicle.set_nitro(id, amount) end

--- Puts the car back on its wheels at a place.
---@param id integer
---@param x number
---@param y number
---@param z number
---@param yaw number
function vehicle.reset(id, x, y, z, yaw) end

--- Holds the car in place (countdowns).
---@param id integer
---@param frozen boolean
function vehicle.freeze(id, frozen) end

--- An AI driver's route: 'x,z x,z ...'.
---@param id integer
---@param route string
---@param loop? boolean
function vehicle.set_route(id, route, loop) end

--- Who an AI driver pursues.
---@param id integer
---@param target integer
function vehicle.set_target(id, target) end

--- Race, Pursuit, Traffic or Off.
---@param id integer
---@param mode string
function vehicle.set_mode(id, mode) end

--- Slows or speeds an AI driver.
---@param id integer
---@param scale number
function vehicle.set_speed_scale(id, scale) end

--- The ship and frame: altitude, speed, fuel, hull, landed, frame, site, ...
---@return table?
function space.state() end

--- touchdown, liftoff, soi:<body>, frame:<body>, site:<name>, reframe, ... since the last call.
---@return string[]
function space.events() end

--- Time warp.
---@param factor number
function space.set_warp(factor) end

--- manual, stabilized, prograde, retrograde or target.
---@param mode string
function space.set_assist(mode) end

--- The navigation target.
---@param body string
function space.set_target(body) end

--- Adds fuel.
---@param amount number
function space.refuel(amount) end

--- Sets the fuel.
---@param amount number
function space.set_fuel(amount) end

--- Changes a ship spec value (upgrades).
---@param field string
---@param value number
function space.tune(field, value) end

--- {thrust, lift, fuel, hull, heat, rcs}
---@return table
function space.spec() end

--- Repairs the hull.
---@param amount number
function space.repair(amount) end

--- Puts the walker in the ship.
function space.board() end

--- Steps out of the ship.
function space.exit() end

--- Lets the player fly (off for menus and cut-scenes).
---@param enabled boolean
function space.set_controls(enabled) end

--- Sets the ship down at a place.
---@param body string
---@param latitude number
---@param longitude number
---@param heading? number
function space.place_landed(body, latitude, longitude, heading) end

--- Puts the ship in a circular orbit.
---@param body string
---@param altitude number
function space.place_orbit(body, altitude) end

--- {radius, gravity, atmosphere, distance, altitude}
---@param name string
---@return table?
function space.body(name) end

--- The generic call the named helpers use.
---@param op string
---@param text? string
---@param ... number
---@return table?
function space.call(op, text, ...) end

--- A burst from this entity's emitter.
---@param count integer
function particles.burst(count) end

--- Starts or stops this entity's emitter.
---@param on boolean
function particles.set_emitting(on) end

--- Starts a move of this fighter's Melee list by name (when it can act).
---@param move string
---@return boolean
function melee.perform(move) end

--- Mode (idle, move, block, stun, airborne, down, getup, dead), combo, energy, energy max, guard 0-1.
---@return string, integer, number, number, number
function melee.state() end

--- The move playing, or "".
---@return string
function melee.move() end

--- Sets its energy (specials spend it).
---@param amount number
function melee.set_energy(amount) end

--- Locks onto a target; no argument releases.
---@param id? integer
function melee.lock(id) end

--- Who it faces and fights.
---@return integer?
function melee.target() end

--- Hands the fighter to (or takes it from) its melee brain.
---@param on boolean
---@param aggression? number
---@param skill? number
function melee.set_ai(on, aggression, skill) end

--- Makes a move marked locked usable; 1 when the move exists.
---@param move string
---@return number?
function melee.unlock(move) end

--- Its poise bar 0-1, and 1 while it's Broken.
---@return number, number
function melee.stagger() end

--- Fires the current weapon (optionally along a direction).
---@param dx? number
---@param dy? number
---@param dz? number
function weapon.fire(dx, dy, dz) end

--- Reloads.
function weapon.reload() end

--- Switches weapon.
---@param slot integer
function weapon.select(slot) end

--- Rounds in the magazine and in reserve.
---@return integer, integer
function weapon.ammo() end

--- Adds reserve rounds.
---@param rounds integer
---@param slot? integer
function weapon.give_ammo(rounds, slot) end

--- A key held this tick, by its code (KeyW, Space, Enter) or its lowercase name (w, enter).
---@param key string
---@return boolean
function input.down(key) end

--- A key pressed this tick.
---@param key string
---@return boolean
function input.pressed(key) end

--- An action's value (axes -1..1, buttons 0/1).
---@param name string
---@return number
function input.action(name) end

--- An action held.
---@param name string
---@return boolean
function input.action_down(name) end

--- An action pressed this tick.
---@param name string
---@return boolean
function input.action_pressed(name) end

--- An action released this tick.
---@param name string
---@return boolean
function input.action_released(name) end

--- The mouse position in the viewport.
---@return number, number
function input.mouse() end

--- A mouse button held.
---@param button integer
---@return boolean
function input.mouse_down(button) end

--- A mouse button pressed this tick.
---@param button integer
---@return boolean
function input.mouse_pressed(button) end

--- Scroll this tick.
---@return number
function input.wheel() end

--- A gamepad button held.
---@param button string
---@return boolean
function input.pad_down(button) end

--- A gamepad button pressed this tick.
---@param button string
---@return boolean
function input.pad_pressed(button) end

--- A gamepad stick axis.
---@param axis string
---@return number
function input.pad_axis(axis) end

--- A gamepad is connected.
---@return boolean
function input.pad_connected() end

--- Captures the mouse for looking around.
---@param locked boolean
function input.lock_mouse(locked) end

--- Stores a value that survives reloads.
---@param key string
---@param value string
function save.set(key, value) end

--- Reads a stored value.
---@param key string
---@return string?
function save.get(key) end

--- Sets the hull exactly (loading a save).
---@param value number
function space.set_hull(value) end

--- Sets the system clock: where every planet is.
---@param seconds number
function space.set_time(seconds) end

--- Puts everyone with a Routine at the stop the clock says.
function space.settle() end

--- Shows a hidden body.
---@param body string
function space.reveal(body) end

--- Every visible body, one per line: name and parent.
function space.bodies() end

--- A route plan to a body: distance, delta-v and the fuel it needs.
---@param body string
function space.plan(body) end

--- Engages or releases the autopilot toward the target.
---@param on boolean
function space.autopilot(on) end

--- Releases the emergency fuel reserve (once, below 35%).
function space.use_reserve() end

--- Repairs (+) or damages (-) engine, rcs, gear or scanner; returns its condition.
---@param part string
---@param amount number
function space.repair_part(part, amount) end

--- Wind on the ship and walker (m/s, site frame).
---@param x number
---@param y number
---@param z number
function space.set_wind(x, y, z) end

--- Whether E boards the ship.
---@param allowed boolean
function space.allow_boarding(allowed) end

--- 0 calm, 1 wary, 2 fleeing, -1 not an animal.
---@param name string
function world.wildlife_state(name) end

--- Reads a line aloud for screen readers and shows it briefly.
---@param text string
function hud.announce(text) end

--- Plays an interface sound cue.
---@param name string
function hud.cue(name) end

--- A waypoint at a place on a planet.
---@param id string
---@param body string
---@param latitude number
---@param longitude number
---@param label string
function hud.waypoint(id, body, latitude, longitude, label) end

--- Removes a waypoint.
---@param id string
function hud.clear_waypoint(id) end

--- off, system, surface or toggle.
---@param mode string
function hud.map(mode) end

--- Shows or hides the minimap.
---@param shown boolean
function hud.minimap(shown) end

--- Opens the player settings panel.
function hud.open_settings() end

--- The helmet visor: on or off, integrity 0-1 (cracks below), frost and heat shimmer 0-1.
---@param helmet boolean
---@param integrity number
---@param frost number
---@param heat number
function hud.visor(helmet, integrity, frost, heat) end

--- auto, on or off.
---@param mode string
function hud.suit_light(mode) end

--- Shows a Ledger system window (title, body lines split by \n); replaces the open one.
---@param title string
---@param body string
function hud.system(title, body) end

--- Closes the Ledger system window.
function hud.system_close() end

--- Plays a comic-panel cutscene: one shot per line, "x y z > tx ty tz | caption | sfx | seconds". Space or Enter skips.
---@param spec string
function hud.panels(spec) end

--- A boss bar (health and stagger) for the named entity; an empty name hides it.
---@param name string
---@param title string
function hud.boss(name, title) end

--- off, title, explore, night, flight, space, signal or tension.
---@param mood string
function audio.music(mood) end

--- An ambience layer's level 0-1: wind, rain, settlement, wildlife or signal.
---@param layer string
---@param level number
function audio.ambience(layer, level) end

--- Weather: rain and fog 0-1, wind in m/s.
---@param rain number
---@param fog number
---@param wind_x number
---@param wind_z number
function fx.weather(rain, fog, wind_x, wind_z) end

--- Dust kicked up on landing: a #rrggbb colour and 0-1 density.
---@param color string
---@param density number
function fx.dust(color, density) end

--- Whether footprints show.
---@param soft boolean
function fx.soft_ground(soft) end

--- Scanner range, scan time and condition multipliers.
---@param range number
---@param time number
---@param condition number
function scanner.tune(range, time, condition) end

--- What scanning the sky identifies.
---@param key string
function scanner.sky_key(key) end

--- Marks a scan id as already known.
---@param id string
function scanner.catalogued(id) end

--- Highlights scatter of these species keys (comma-separated); empty label stops.
---@param label string
---@param range number
---@param keys string
function scanner.prospect(label, range, keys) end

--- Once, when play starts.
function on_start() end

--- Every tick (1/60 s).
---@param dt number
function on_tick(dt) end

--- A UI element was used, or the host sent an event.
---@param name string
---@param value any
function on_ui(name, value) end

--- Another script called world.send.
---@param name string
---@param value any
---@param sender integer
function on_message(name, value, sender) end

--- This entity was hurt.
---@param amount number
---@param attacker integer?
function on_damaged(amount, attacker) end

--- Health reached 0.
---@param attacker integer?
function on_death(attacker) end

--- This entity defeated another.
---@param victim integer
function on_kill(victim) end

--- This fighter's blow met someone: hit, blocked, parried, dodged or guard_break.
---@param target integer
---@param move string
---@param damage number
---@param outcome string
function on_melee_hit(target, move, damage, outcome) end

--- Started touching (also _stay, _exit).
---@param other integer
function on_collision_enter(other) end

--- Something entered this trigger (also _stay, _exit).
---@param other integer
function on_trigger_enter(other) end

--- The Animator entered a state.
---@param state string
function on_anim_state(state) end

--- An Animator event fired.
---@param name string
function on_anim_event(name) end

--- Calls fn once later; cancel(handle) stops it.
---@param seconds number
---@param fn function
---@return integer
function after(seconds, fn) end

--- Calls fn repeatedly.
---@param seconds number
---@param fn function
---@return integer
function every(seconds, fn) end

--- Runs fn as a coroutine that can wait(seconds).
---@param fn function
function start(fn) end
