// Generated by tools/bridge/gen_fields.mjs from tools/bridge/fields.mjs. Don't edit.

// editor_space_value(field)
export const SpaceField = {
  // 1 while the player flies the ship
  piloting: 0,
  // ship position in the site frame
  shipX: 1,
  shipY: 2,
  shipZ: 3,
  // ship attitude quaternion in the site frame
  attitudeX: 4,
  attitudeY: 5,
  attitudeZ: 6,
  attitudeW: 7,
  // metres above the reference body's surface
  altitude: 8,
  // speed relative to the reference body (m/s)
  speed: 9,
  verticalSpeed: 10,
  groundSpeed: 11,
  // 0..1
  throttle: 12,
  // 0..1 of the tank
  fuel: 13,
  // 0..1
  hull: 14,
  heat: 15,
  airDensity: 16,
  // time warp factor
  warp: 17,
  // 0 manual, 1 stabilized, 2 prograde, 3 retrograde, 4 target
  assist: 18,
  landed: 19,
  periapsis: 20,
  apoapsis: 21,
  orbitClosed: 22,
  // body index, -1 the star
  referenceBody: 23,
  gForce: 24,
  engineOn: 25,
  bellyThrust: 26,
  // seconds
  systemTime: 27,
  destroyed: 28,
  targetBody: 29,
  // to the target's surface (m)
  targetDistance: 30,
  // from the site origin (m)
  siteDistance: 31,
  orbitPeriod: 32,
  eccentricity: 33,
  referenceRadius: 34,
  hasSpaceSystem: 35,
  bodyCount: 36,
  // 1 when the frame follows the ship or walker away from the authored site
  away: 37,
  // changes whenever the frame moves
  frameGeneration: 38,
  frameBody: 39,
  // -1 home, -2 the wilds, else the Site number
  activeSite: 40,
  autopilot: 41,
  engineCondition: 42,
  rcsCondition: 43,
  gearCondition: 44,
  scannerCondition: 45,
  windSpeed: 46,
  // degrees under the ship
  groundSlope: 47,
  // the gear's limits: sink m/s
  landSink: 48,
  // slope degrees
  landSlope: 49,
  // drift m/s
  landDrift: 50,
  waterBelow: 51,
  // the walker's shift in the latest on-foot re-anchor
  reframeShiftX: 52,
  reframeShiftY: 53,
  reframeShiftZ: 54,
  // degrees, body-fixed
  frameLatitude: 55,
  frameLongitude: 56,
  // the turn about the vertical in that re-anchor (radians)
  reframeYaw: 57,
} as const;

// editor_value(index, field)
export const EntityField = {
  // position
  x: 0,
  y: 1,
  z: 2,
  // current / max, -1 without Health
  health: 3,
  // radians
  headingYaw: 4,
  // AIState order (Idle, Walking, ...), -1 without an AI
  aiState: 5,
} as const;

// editor_fighter_value(index, field)
export const FighterField = {
  // 1 with a Melee fighter
  has: 0,
  // 0 idle, 1 move, 2 block, 3 stun, 4 airborne, 5 down, 6 getup, 7 dead
  mode: 1,
  // the move playing, -1 none
  move: 2,
  // 0..1 through the move
  progress: 3,
  // facing, radians (sin, 0, cos)
  yaw: 4,
  // 0..1
  energy: 5,
  // hits in the current string
  combo: 6,
  // seconds frozen
  hitstop: 7,
  // 0 none, 1 light, 2 heavy, 3 launched, 4 knockdown, 5 guard_break, 6 parried
  stunKind: 8,
  // the Player's locked-on entity index, -1 none
  lockTarget: 9,
  // 0..1
  guard: 10,
  invulnerable: 11,
  // seconds into the move / stun / down / getup
  time: 12,
  // the entity it faces and fights, -1 none
  target: 13,
  // 1 while the move's blow is live
  active: 14,
  team: 15,
  // seconds of hit-stun left
  stunLeft: 16,
} as const;

// editor_melee_event(index, field)
export const MeleeEventField = {
  // 0 start, 1 hit, 2 blocked, 3 parried, 4 dodged, 5 guard_break, 6 fire, 7 land, 8 ko
  kind: 0,
  attacker: 1,
  target: 2,
  // where it landed
  x: 3,
  y: 4,
  z: 5,
  // damage; start: the move's seconds; fire: speed
  value: 6,
  move: 7,
  // 1 finisher, 2 launch, 4 knockdown, 8 heavy, 16 killed
  flags: 8,
} as const;
