// What each component is for, and the fields that need explaining (0.77.0).
// The inspector shows these as tooltips and a line under each card's title;
// tools/gen_component_docs.mjs builds docs/COMPONENTS.md from the same table,
// so the editor and the reference never disagree.

export const componentHelp: Record<string, string> = {
  Transform: "Where the entity is (world units, Y up).",
  Rotation: "Which way it faces (radians about each axis).",
  Scale: "Its size; also the default size of instances spawned from a prefab.",
  Velocity: "Movement in units per second, applied every tick.",
  Acceleration: "Change in velocity per second (e.g. gravity on a projectile).",
  RigidBody: "Lets physics move it. Dynamic bodies fall and get pushed; kinematic ones only move when told.",
  Collider: "Its solid shape for physics, or a trigger volume that reports overlaps to scripts.",
  Health: "Hit points. At 0 the entity is defeated (scripts get on_death).",
  AIState: "A simple wander/chase/flee brain for walkers and animals.",
  Pedestrian: "Makes it a walking person, with a pace and look.",
  Player: "The entity the keyboard and mouse control.",
  Vehicle: "A drivable car: speed, grip, nitro and gears.",
  AnimationState: "Pins one clip of an animated model (advanced; the Renderable card's clip picker is the usual way).",
  Renderable: "What it looks like: a box or a catalog model.",
  Light: "A point, spot or directional light.",
  Particles: "An emitter: sparkles, smoke, fire or confetti.",
  UI: "An on-screen element: text, button, bar, slider, toggle or image.",
  Script: "Lua code that runs while playing (on_start, on_tick, on_ui, ...). See the API reference.",
  Sound: "A sound from the catalog, played in the world.",
  Environment: "The sky, sun, fog and shadows for the whole scene.",
  Camera: "A game camera; the highest-priority one renders while playing.",
  Material: "Colour, roughness, metalness, glow and texture overrides.",
  Animator: "A state machine that picks clips: states, transitions on triggers or the clip's end, and events.",
  CameraFollow: "A third-person camera rig that follows a target, with smoothing, collision and orbit.",
  CharacterController: "First- or third-person walking: speeds, jump, crouch, step height and look.",
  Weapons: "Guns and melee the entity carries.",
  AICombat: "A soldier brain: patrol, guard or hunt; sight, hearing, cover and accuracy.",
  Driver: "An AI driver that races a route, pursues a target or drives in traffic.",
  ModelInstances: "Many copies of catalog models placed cheaply (forests, rocks): one line per copy.",
  SpaceSystem: "A star system: planets and moons on rails, a landing site, and spaceflight.",
  Spaceship: "The ship the player flies in a SpaceSystem.",
  Scannable: "Something the scanner can identify; scripts get the scan id.",
  Site: "A place on a planet of the SpaceSystem; its children are built there.",
  Routine: "A daily schedule: the entity walks to each stop at its hour and does the activity there.",
  Wildlife: "An animal that grows wary of the player and flees, staying near home.",
  Terrain: "A heightfield ground with noise, sculpting, colour bands and scattered models.",
  AudioSettings: "Volumes for the mixer buses, room reverb and wall muffling.",
  PostProcessing: "Screen effects: bloom, ambient occlusion, colour grading, vignette, grain.",
  InputActions: "Named actions (jump, fire, ...) and the keys and buttons bound to them.",
  Trail: "A ribbon that follows the entity as it moves.",
};

export const fieldHelp: Record<string, string> = {
  "Routine.stops":
    "Each stop is an hour (0-24), an x and z position, and an optional activity (sit, talk, work, hammer, graze). The entity heads for the latest stop whose hour has passed.",
  "Routine.speed": "Walking speed in metres per second.",
  "Wildlife.wary": "Within this distance of a threat the animal stops and watches.",
  "Wildlife.flee": "Within this distance it runs (twice as far from a sprinting player).",
  "Wildlife.leash": "It never runs farther than this from where it started.",
  "ModelInstances.instances": "One copy per line: model id, x, z, then optional yaw (degrees), scale and 'solid'.",
  "Terrain.scatter": "One rule per line: model id, density (per 100 m²), optional height range, steepest slope and 'collide'.",
  "SpaceSystem.bodies":
    "One body per line with key=value pairs (name, parent, orbit, period, radius, g, air, craters, ...). Errors are listed under the field.",
  "Animator.graph": "Lines like 'state idle clip=idle', 'any -> hop when trigger go', 'hop -> idle when end', 'event hop 0.5 midway'.",
  "Driver.route": "Waypoints as x,z pairs separated by spaces.",
  "AICombat.patrol": "Entity names to walk between, comma-separated.",
  "CameraFollow.target": "The name of the entity to follow; empty follows the Player.",
  "Weapons.loadout": "One weapon per line: name: key=value ... (damage, rate, range, magazine, ...).",
  "Collider.mask": "Which layers this collides with, as a bitmask (4294967295 = all).",
  "Material.parts": "Only tint the model's parts with these names, e.g. TunicCloth,MantleCloth.",
  "Script.source":
    "Lua. Callbacks: on_start, on_tick(dt), on_ui, on_message, on_damaged, on_death, on_kill, on_collision_enter/stay/exit, on_trigger_enter/stay/exit, on_anim_state, on_anim_event. Tables: world, input, ui, sound, camera, anim, physics, weapon, vehicle, particles, game, save, space, host. Help → Script API lists every function.",
};
