// Generated by tools/bridge/gen_exports.mjs from apps/editor/runtime/bridge*.cpp. Don't edit.
// 90 exports: 62 called directly, 28 through ccall (they take or return strings).

export interface RuntimeExports {
  _editor_begin(): void;
  _editor_add(x: number, y: number, z: number, vx: number, vy: number, vz: number, sx: number, sy: number, sz: number, isChild: number, isPlayer: number, isCollider: number, hpCurrent: number, hpMax: number, isVehicle: number, isAi: number, isPedestrian: number, colliderShape: number, colliderRadius: number, vehicleArchetype: number, pedestrianArchetype: number): number;
  _editor_set_body(index: number, authored: number, mass: number, dynamic: number): void;
  _editor_set_collider(index: number, isTrigger: number, layer: number, mask: number, bounciness: number): void;
  _editor_set_rotation(index: number, x: number, y: number, z: number): void;
  _editor_set_controller(index: number, mode: number, walk: number, sprint: number, crouch: number, jump: number, stand: number, crouched: number, step: number, accel: number, air: number): void;
  _editor_add_obstacle(x: number, y: number, z: number, sx: number, sy: number, sz: number): void;
  _editor_line_blocked(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number): number;
  _editor_terrain_height(x: number, z: number): number;
  _editor_commit(): number;
  _editor_tick(): void;
  _editor_input_begin_frame(): void;
  _editor_set_camera_forward(x: number, z: number): void;
  _editor_set_look(yaw: number, pitch: number): void;
  _editor_controller_value(index: number, field: number): number;
  _editor_key(code: number, down: number): void;
  _editor_input_mouse_move(x: number, y: number, dx: number, dy: number): void;
  _editor_input_mouse_button(button: number, down: number, x: number, y: number): void;
  _editor_input_wheel(dx: number, dy: number): void;
  _editor_input_gamepad_connected(connected: number): void;
  _editor_input_gamepad_button(button: number, down: number): void;
  _editor_input_gamepad_axis(axis: number, value: number): void;
  _editor_value(index: number, field: number): number;
  _editor_alive(index: number): number;
  _editor_count(): number;
  _editor_snapshot(): number;
  _editor_take_dirty_saves(): number;
  _editor_entity_count(): number;
  _editor_take_commands(): number;
  _editor_command_entity(index: number): number;
  _editor_set_sim_stride(stride: number): void;
  _editor_projectile_count(): number;
  _editor_projectile_value(index: number, field: number): number;
  _editor_set_soldier(index: number, team: number, behavior: number, sight: number, fov: number, hearing: number, reaction: number, accuracy: number, preferred: number, speed: number, burst: number, burstPause: number, useCover: number, fleeHealth: number, melee: number): void;
  _editor_set_car(index: number, yaw: number, topSpeed: number, acceleration: number, braking: number, grip: number, driftGrip: number, steering: number, nitroBoost: number, nitroSeconds: number, gears: number): void;
  _editor_set_driver(index: number, mode: number, loop: number, skill: number, aggression: number, speedScale: number): void;
  _editor_vehicle_value(index: number, field: number): number;
  _editor_soldier_value(index: number, field: number): number;
  _editor_weapon_value(index: number, field: number): number;
  _editor_take_weapon_events(): number;
  _editor_weapon_event(index: number, field: number): number;
  _editor_space_begin(starGm: number, siteBody: number, siteLatitude: number, siteLongitude: number, siteRadius: number, evaRange: number, startTime: number): void;
  _editor_space_stick(yaw: number, pitch: number): void;
  _editor_space_body_sea(seaLevel: number): void;
  _editor_space_body_features(craters: number, rifts: number, dunes: number, day: number): void;
  _editor_space_body_hidden(hidden: number): void;
  _editor_space_member(index: number, site: number): void;
  _editor_routine_stop(index: number): number;
  _editor_set_wildlife(index: number, wary: number, flee: number, speed: number, leash: number): void;
  _editor_push(index: number, dx: number, dz: number): void;
  _editor_wildlife_state(index: number): number;
  _editor_set_spaceship(index: number, heading: number, mass: number, thrust: number, liftThrust: number, rcs: number, maxRate: number, fuel: number, burn: number, hull: number, gearClearance: number, startPiloting: number, startOrbit: number): void;
  _editor_space_value(field: number): number;
  _editor_space_body_value(index: number, field: number): number;
  _editor_space_frame(field: number): number;
  _editor_space_body_spin(index: number, field: number): number;
  _editor_planet_lava(index: number, x: number, y: number, z: number): number;
  _editor_planet_height(index: number, x: number, y: number, z: number): number;
  _editor_space_ground(x: number, z: number): number;
  _editor_space_wet(x: number, z: number): number;
  _editor_space_path(count: number, horizon: number): number;
  _editor_space_path_value(i: number, axis: number): number;
}

// Called with runtime.ccall(name, ...) because a string crosses the boundary.
export const ccallExports = {
  editor_set_terrain: { returns: "void", args: ["number", "number", "number", "number", "number", "string"] },
  editor_set_script_source: { returns: "void", args: ["number", "string"] },
  editor_set_script_props: { returns: "void", args: ["number", "string"] },
  editor_set_name: { returns: "void", args: ["number", "string"] },
  editor_template_begin: { returns: "void", args: ["string"] },
  editor_input_key: { returns: "void", args: ["string", "number"] },
  editor_set_input_bindings: { returns: "void", args: ["string"] },
  editor_bindings_error: { returns: "string", args: [] },
  editor_action_value: { returns: "number", args: ["string"] },
  editor_script_key: { returns: "void", args: ["string", "number"] },
  editor_script_error: { returns: "string", args: ["number"] },
  editor_take_animation_request: { returns: "string", args: ["number"] },
  editor_seed_save: { returns: "void", args: ["string", "string"] },
  editor_dirty_save_key: { returns: "string", args: ["number"] },
  editor_dirty_save_value: { returns: "string", args: ["number"] },
  editor_spawned_prefab: { returns: "string", args: ["number"] },
  editor_command_text: { returns: "string", args: ["number", "number"] },
  editor_script_notify: { returns: "void", args: ["number", "string", "string"] },
  editor_ui_event: { returns: "void", args: ["string", "string"] },
  editor_profile_text: { returns: "string", args: [] },
  editor_set_soldier_patrol: { returns: "void", args: ["number", "string"] },
  editor_set_driver_text: { returns: "void", args: ["number", "number", "string"] },
  editor_set_weapons: { returns: "void", args: ["number", "string"] },
  editor_weapons_error: { returns: "string", args: [] },
  editor_weapon_text: { returns: "string", args: ["number", "number", "number"] },
  editor_space_body: { returns: "void", args: ["string", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number"] },
  editor_space_site: { returns: "void", args: ["number", "string", "number", "number", "number", "number"] },
  editor_set_routine: { returns: "void", args: ["number", "string", "number"] },
} as const;
export type CcallExport = keyof typeof ccallExports;
