// Generated by tools/script_api/gen.mjs from tools/script_api/api.mjs. Don't edit.
export interface ScriptApiEntry {
  name: string;
  signature: string;
  doc: string;
  group: string;
}

export const scriptApi: ScriptApiEntry[] = [
  {
    "name": "on_start",
    "signature": "on_start()",
    "doc": "Once, when play starts.",
    "group": "callbacks"
  },
  {
    "name": "on_tick",
    "signature": "on_tick(dt: number)",
    "doc": "Every tick (1/60 s).",
    "group": "callbacks"
  },
  {
    "name": "on_ui",
    "signature": "on_ui(name: string, value: any)",
    "doc": "A UI element was used, or the host sent an event.",
    "group": "callbacks"
  },
  {
    "name": "on_message",
    "signature": "on_message(name: string, value: any, sender: integer)",
    "doc": "Another script called world.send.",
    "group": "callbacks"
  },
  {
    "name": "on_damaged",
    "signature": "on_damaged(amount: number, attacker: integer?)",
    "doc": "This entity was hurt.",
    "group": "callbacks"
  },
  {
    "name": "on_death",
    "signature": "on_death(attacker: integer?)",
    "doc": "Health reached 0.",
    "group": "callbacks"
  },
  {
    "name": "on_kill",
    "signature": "on_kill(victim: integer)",
    "doc": "This entity defeated another.",
    "group": "callbacks"
  },
  {
    "name": "on_melee_hit",
    "signature": "on_melee_hit(target: integer, move: string, damage: number, outcome: string)",
    "doc": "This fighter's blow met someone: hit, blocked, parried, dodged or guard_break.",
    "group": "callbacks"
  },
  {
    "name": "on_collision_enter",
    "signature": "on_collision_enter(other: integer)",
    "doc": "Started touching (also _stay, _exit).",
    "group": "callbacks"
  },
  {
    "name": "on_trigger_enter",
    "signature": "on_trigger_enter(other: integer)",
    "doc": "Something entered this trigger (also _stay, _exit).",
    "group": "callbacks"
  },
  {
    "name": "on_anim_state",
    "signature": "on_anim_state(state: string)",
    "doc": "The Animator entered a state.",
    "group": "callbacks"
  },
  {
    "name": "on_anim_event",
    "signature": "on_anim_event(name: string)",
    "doc": "An Animator event fired.",
    "group": "callbacks"
  },
  {
    "name": "after",
    "signature": "after(seconds: number, fn: function): integer",
    "doc": "Calls fn once later; cancel(handle) stops it.",
    "group": "callbacks"
  },
  {
    "name": "every",
    "signature": "every(seconds: number, fn: function): integer",
    "doc": "Calls fn repeatedly.",
    "group": "callbacks"
  },
  {
    "name": "start",
    "signature": "start(fn: function)",
    "doc": "Runs fn as a coroutine that can wait(seconds).",
    "group": "callbacks"
  },
  {
    "name": "world.find",
    "signature": "world.find(name: string): integer?",
    "doc": "The id of the first entity with this name.",
    "group": "world"
  },
  {
    "name": "world.name",
    "signature": "world.name(id: integer): string?",
    "doc": "An entity's name.",
    "group": "world"
  },
  {
    "name": "world.alive",
    "signature": "world.alive(id: integer): boolean",
    "doc": "False once the entity is destroyed.",
    "group": "world"
  },
  {
    "name": "world.position",
    "signature": "world.position(id: integer): number?, number?, number?",
    "doc": "Where the entity is.",
    "group": "world"
  },
  {
    "name": "world.set_position",
    "signature": "world.set_position(id: integer, x: number, y: number, z: number)",
    "doc": "Moves the entity.",
    "group": "world"
  },
  {
    "name": "world.velocity",
    "signature": "world.velocity(id: integer): number?, number?, number?",
    "doc": "Its velocity (m/s).",
    "group": "world"
  },
  {
    "name": "world.set_velocity",
    "signature": "world.set_velocity(id: integer, x: number, y: number, z: number)",
    "doc": "Sets its velocity.",
    "group": "world"
  },
  {
    "name": "world.spawn",
    "signature": "world.spawn(prefab: string, x: number, y: number, z: number): integer?",
    "doc": "A new instance of a prefab; returns its id.",
    "group": "world"
  },
  {
    "name": "world.destroy",
    "signature": "world.destroy(id: integer)",
    "doc": "Removes the entity.",
    "group": "world"
  },
  {
    "name": "world.health",
    "signature": "world.health(id: integer): number?, number?",
    "doc": "Current and maximum health.",
    "group": "world"
  },
  {
    "name": "world.damage",
    "signature": "world.damage(id: integer, amount: number)",
    "doc": "Hurts the entity (on_damaged, then on_death at 0).",
    "group": "world"
  },
  {
    "name": "world.heal",
    "signature": "world.heal(id: integer, amount: number)",
    "doc": "Restores health up to its maximum.",
    "group": "world"
  },
  {
    "name": "world.give_ammo",
    "signature": "world.give_ammo(id: integer, rounds: integer, slot?: integer)",
    "doc": "Adds reserve rounds to its weapon.",
    "group": "world"
  },
  {
    "name": "world.raycast",
    "signature": "world.raycast(ox, oy, oz, dx, dy, dz, max: number, mask?: integer): table?",
    "doc": "The first hit along a ray: {id, x, y, z, nx, ny, nz, distance}.",
    "group": "world"
  },
  {
    "name": "world.overlap",
    "signature": "world.overlap(x, y, z, radius: number, mask?: integer): integer[]",
    "doc": "Entities with colliders inside a sphere.",
    "group": "world"
  },
  {
    "name": "world.send",
    "signature": "world.send(id: integer, name: string, value?: any)",
    "doc": "Calls the entity's on_message(name, value, sender).",
    "group": "world"
  },
  {
    "name": "world.path",
    "signature": "world.path(x, y, z, tx, ty, tz: number): table[]?",
    "doc": "Waypoints {x, y, z} around obstacles, or nil when unreachable.",
    "group": "world"
  },
  {
    "name": "world.set_clock",
    "signature": "world.set_clock(hours: number): number",
    "doc": "The scene clock that Routines follow.",
    "group": "world"
  },
  {
    "name": "host.send",
    "signature": "host.send(kind: string, text: string)",
    "doc": "A raw message to the host (the named helpers below send these for you).",
    "group": "host"
  },
  {
    "name": "physics.add_force",
    "signature": "physics.add_force(id: integer, x: number, y: number, z: number)",
    "doc": "A force for this tick.",
    "group": "physics"
  },
  {
    "name": "physics.add_impulse",
    "signature": "physics.add_impulse(id: integer, x: number, y: number, z: number)",
    "doc": "An instant change of momentum.",
    "group": "physics"
  },
  {
    "name": "sound.play",
    "signature": "sound.play(name: string)",
    "doc": "Plays a sound from the catalog.",
    "group": "sound"
  },
  {
    "name": "sound.play_at",
    "signature": "sound.play_at(name: string, x: number, y: number, z: number, volume?: number)",
    "doc": "Plays a sound in the world.",
    "group": "sound"
  },
  {
    "name": "sound.volume",
    "signature": "sound.volume(bus: string, level: number)",
    "doc": "Sets a mixer bus volume 0-1 (master, sfx, music, ambient, ui).",
    "group": "sound"
  },
  {
    "name": "ui.set_text",
    "signature": "ui.set_text(name: string, text: string)",
    "doc": "Changes a UI element's text.",
    "group": "ui"
  },
  {
    "name": "ui.set_value",
    "signature": "ui.set_value(name: string, value: number)",
    "doc": "Sets a Bar, Slider or Toggle (0-1).",
    "group": "ui"
  },
  {
    "name": "ui.set_visible",
    "signature": "ui.set_visible(name: string, visible: boolean)",
    "doc": "Shows or hides a UI element.",
    "group": "ui"
  },
  {
    "name": "ui.marker",
    "signature": "ui.marker(name: string, x: number, y: number, z: number, label?: string)",
    "doc": "An on-screen waypoint at a world position, pinned to the screen edge when off screen.",
    "group": "ui"
  },
  {
    "name": "ui.clear_marker",
    "signature": "ui.clear_marker(id: string)",
    "doc": "Removes a marker.",
    "group": "ui"
  },
  {
    "name": "game.pause",
    "signature": "game.pause()",
    "doc": "Pauses play.",
    "group": "game"
  },
  {
    "name": "game.resume",
    "signature": "game.resume()",
    "doc": "Resumes play.",
    "group": "game"
  },
  {
    "name": "anim.set",
    "signature": "anim.set(name: string, value: any)",
    "doc": "Sets an Animator parameter.",
    "group": "anim"
  },
  {
    "name": "anim.trigger",
    "signature": "anim.trigger(name: string)",
    "doc": "Fires an Animator trigger.",
    "group": "anim"
  },
  {
    "name": "camera.shake",
    "signature": "camera.shake(intensity?: number, seconds?: number)",
    "doc": "Shakes the game camera (defaults 0.3, 0.4 s).",
    "group": "camera"
  },
  {
    "name": "vehicle.state",
    "signature": "vehicle.state(id: integer): number, number, integer, number, number, boolean, boolean, number, number",
    "doc": "speed, forward, gear, rpm, nitro, drifting, boosting, yaw, slip.",
    "group": "vehicle"
  },
  {
    "name": "vehicle.set_nitro",
    "signature": "vehicle.set_nitro(id: integer, amount: number)",
    "doc": "Refills the nitro tank.",
    "group": "vehicle"
  },
  {
    "name": "vehicle.reset",
    "signature": "vehicle.reset(id: integer, x: number, y: number, z: number, yaw: number)",
    "doc": "Puts the car back on its wheels at a place.",
    "group": "vehicle"
  },
  {
    "name": "vehicle.freeze",
    "signature": "vehicle.freeze(id: integer, frozen: boolean)",
    "doc": "Holds the car in place (countdowns).",
    "group": "vehicle"
  },
  {
    "name": "vehicle.set_route",
    "signature": "vehicle.set_route(id: integer, route: string, loop?: boolean)",
    "doc": "An AI driver's route: 'x,z x,z ...'.",
    "group": "vehicle"
  },
  {
    "name": "vehicle.set_target",
    "signature": "vehicle.set_target(id: integer, target: integer)",
    "doc": "Who an AI driver pursues.",
    "group": "vehicle"
  },
  {
    "name": "vehicle.set_mode",
    "signature": "vehicle.set_mode(id: integer, mode: string)",
    "doc": "Race, Pursuit, Traffic or Off.",
    "group": "vehicle"
  },
  {
    "name": "vehicle.set_speed_scale",
    "signature": "vehicle.set_speed_scale(id: integer, scale: number)",
    "doc": "Slows or speeds an AI driver.",
    "group": "vehicle"
  },
  {
    "name": "space.state",
    "signature": "space.state(): table?",
    "doc": "The ship and frame: altitude, speed, fuel, hull, landed, frame, site, ...",
    "group": "space"
  },
  {
    "name": "space.events",
    "signature": "space.events(): string[]",
    "doc": "touchdown, liftoff, soi:<body>, frame:<body>, site:<name>, reframe, ... since the last call.",
    "group": "space"
  },
  {
    "name": "space.set_warp",
    "signature": "space.set_warp(factor: number)",
    "doc": "Time warp.",
    "group": "space"
  },
  {
    "name": "space.set_assist",
    "signature": "space.set_assist(mode: string)",
    "doc": "manual, stabilized, prograde, retrograde or target.",
    "group": "space"
  },
  {
    "name": "space.set_target",
    "signature": "space.set_target(body: string)",
    "doc": "The navigation target.",
    "group": "space"
  },
  {
    "name": "space.refuel",
    "signature": "space.refuel(amount: number)",
    "doc": "Adds fuel.",
    "group": "space"
  },
  {
    "name": "space.set_fuel",
    "signature": "space.set_fuel(amount: number)",
    "doc": "Sets the fuel.",
    "group": "space"
  },
  {
    "name": "space.tune",
    "signature": "space.tune(field: string, value: number)",
    "doc": "Changes a ship spec value (upgrades).",
    "group": "space"
  },
  {
    "name": "space.spec",
    "signature": "space.spec(): table",
    "doc": "{thrust, lift, fuel, hull, heat, rcs}",
    "group": "space"
  },
  {
    "name": "space.repair",
    "signature": "space.repair(amount: number)",
    "doc": "Repairs the hull.",
    "group": "space"
  },
  {
    "name": "space.board",
    "signature": "space.board()",
    "doc": "Puts the walker in the ship.",
    "group": "space"
  },
  {
    "name": "space.exit",
    "signature": "space.exit()",
    "doc": "Steps out of the ship.",
    "group": "space"
  },
  {
    "name": "space.set_controls",
    "signature": "space.set_controls(enabled: boolean)",
    "doc": "Lets the player fly (off for menus and cut-scenes).",
    "group": "space"
  },
  {
    "name": "space.place_landed",
    "signature": "space.place_landed(body: string, latitude: number, longitude: number, heading?: number)",
    "doc": "Sets the ship down at a place.",
    "group": "space"
  },
  {
    "name": "space.place_orbit",
    "signature": "space.place_orbit(body: string, altitude: number)",
    "doc": "Puts the ship in a circular orbit.",
    "group": "space"
  },
  {
    "name": "space.body",
    "signature": "space.body(name: string): table?",
    "doc": "{radius, gravity, atmosphere, distance, altitude}",
    "group": "space"
  },
  {
    "name": "space.call",
    "signature": "space.call(op: string, text?: string, ...: number): table?",
    "doc": "The generic call the named helpers use.",
    "group": "space"
  },
  {
    "name": "particles.burst",
    "signature": "particles.burst(count: integer)",
    "doc": "A burst from this entity's emitter.",
    "group": "particles"
  },
  {
    "name": "particles.set_emitting",
    "signature": "particles.set_emitting(on: boolean)",
    "doc": "Starts or stops this entity's emitter.",
    "group": "particles"
  },
  {
    "name": "melee.perform",
    "signature": "melee.perform(move: string): boolean",
    "doc": "Starts a move of this fighter's Melee list by name (when it can act).",
    "group": "melee"
  },
  {
    "name": "melee.state",
    "signature": "melee.state(): string, integer, number, number, number",
    "doc": "Mode (idle, move, block, stun, airborne, down, getup, dead), combo, energy, energy max, guard 0-1.",
    "group": "melee"
  },
  {
    "name": "melee.move",
    "signature": "melee.move(): string",
    "doc": "The move playing, or \"\".",
    "group": "melee"
  },
  {
    "name": "melee.set_energy",
    "signature": "melee.set_energy(amount: number)",
    "doc": "Sets its energy (specials spend it).",
    "group": "melee"
  },
  {
    "name": "melee.lock",
    "signature": "melee.lock(id?: integer)",
    "doc": "Locks onto a target; no argument releases.",
    "group": "melee"
  },
  {
    "name": "melee.target",
    "signature": "melee.target(): integer?",
    "doc": "Who it faces and fights.",
    "group": "melee"
  },
  {
    "name": "melee.set_ai",
    "signature": "melee.set_ai(on: boolean, aggression?: number, skill?: number)",
    "doc": "Hands the fighter to (or takes it from) its melee brain.",
    "group": "melee"
  },
  {
    "name": "melee.unlock",
    "signature": "melee.unlock(move: string): number?",
    "doc": "Makes a move marked locked usable; 1 when the move exists.",
    "group": "melee"
  },
  {
    "name": "melee.stagger",
    "signature": "melee.stagger(): number, number",
    "doc": "Its poise bar 0-1, and 1 while it's Broken.",
    "group": "melee"
  },
  {
    "name": "melee.mana",
    "signature": "melee.mana(add?: number): number, number",
    "doc": "Adds mana (a potion; capped at the max) and returns its mana and max.",
    "group": "melee"
  },
  {
    "name": "melee.follow",
    "signature": "melee.follow(leader?: integer, slot?: integer)",
    "doc": "Makes this AI fighter an ally of the leader: with no hostile within reach it walks to its slot (0 left, 1 right, 2 behind) and won't chase hostiles more than 16 m from the leader; nil stops it.",
    "group": "melee"
  },
  {
    "name": "melee.tune",
    "signature": "melee.tune(damage: number, speed: number, crit: number, skill: number, health_max?: number, mana_max?: number): number, number, number, number",
    "doc": "Stats: damage dealt (times), its clock speed (0.5-2: attacks, dodges, cooldowns), crit chance 0-1 (1.5x), skill damage (times, moves that cost mana), and optionally max health and mana. -1 keeps one as is.",
    "group": "melee"
  },
  {
    "name": "weapon.fire",
    "signature": "weapon.fire(dx?: number, dy?: number, dz?: number)",
    "doc": "Fires the current weapon (optionally along a direction).",
    "group": "weapon"
  },
  {
    "name": "weapon.reload",
    "signature": "weapon.reload()",
    "doc": "Reloads.",
    "group": "weapon"
  },
  {
    "name": "weapon.select",
    "signature": "weapon.select(slot: integer)",
    "doc": "Switches weapon.",
    "group": "weapon"
  },
  {
    "name": "weapon.ammo",
    "signature": "weapon.ammo(): integer, integer",
    "doc": "Rounds in the magazine and in reserve.",
    "group": "weapon"
  },
  {
    "name": "weapon.give_ammo",
    "signature": "weapon.give_ammo(rounds: integer, slot?: integer)",
    "doc": "Adds reserve rounds.",
    "group": "weapon"
  },
  {
    "name": "input.down",
    "signature": "input.down(key: string): boolean",
    "doc": "A key held this tick, by its code (KeyW, Space, Enter) or its lowercase name (w, enter).",
    "group": "input"
  },
  {
    "name": "input.pressed",
    "signature": "input.pressed(key: string): boolean",
    "doc": "A key pressed this tick.",
    "group": "input"
  },
  {
    "name": "input.action",
    "signature": "input.action(name: string): number",
    "doc": "An action's value (axes -1..1, buttons 0/1).",
    "group": "input"
  },
  {
    "name": "input.action_down",
    "signature": "input.action_down(name: string): boolean",
    "doc": "An action held.",
    "group": "input"
  },
  {
    "name": "input.action_pressed",
    "signature": "input.action_pressed(name: string): boolean",
    "doc": "An action pressed this tick.",
    "group": "input"
  },
  {
    "name": "input.action_released",
    "signature": "input.action_released(name: string): boolean",
    "doc": "An action released this tick.",
    "group": "input"
  },
  {
    "name": "input.mouse",
    "signature": "input.mouse(): number, number",
    "doc": "The mouse position in the viewport.",
    "group": "input"
  },
  {
    "name": "input.mouse_down",
    "signature": "input.mouse_down(button: integer): boolean",
    "doc": "A mouse button held.",
    "group": "input"
  },
  {
    "name": "input.mouse_pressed",
    "signature": "input.mouse_pressed(button: integer): boolean",
    "doc": "A mouse button pressed this tick.",
    "group": "input"
  },
  {
    "name": "input.wheel",
    "signature": "input.wheel(): number",
    "doc": "Scroll this tick.",
    "group": "input"
  },
  {
    "name": "input.pad_down",
    "signature": "input.pad_down(button: string): boolean",
    "doc": "A gamepad button held.",
    "group": "input"
  },
  {
    "name": "input.pad_pressed",
    "signature": "input.pad_pressed(button: string): boolean",
    "doc": "A gamepad button pressed this tick.",
    "group": "input"
  },
  {
    "name": "input.pad_axis",
    "signature": "input.pad_axis(axis: string): number",
    "doc": "A gamepad stick axis.",
    "group": "input"
  },
  {
    "name": "input.pad_connected",
    "signature": "input.pad_connected(): boolean",
    "doc": "A gamepad is connected.",
    "group": "input"
  },
  {
    "name": "input.lock_mouse",
    "signature": "input.lock_mouse(locked: boolean)",
    "doc": "Captures the mouse for looking around.",
    "group": "input"
  },
  {
    "name": "save.set",
    "signature": "save.set(key: string, value: string)",
    "doc": "Stores a value that survives reloads.",
    "group": "save"
  },
  {
    "name": "save.get",
    "signature": "save.get(key: string): string?",
    "doc": "Reads a stored value.",
    "group": "save"
  },
  {
    "name": "space.set_hull",
    "signature": "space.set_hull(value: number)",
    "doc": "Sets the hull exactly (loading a save).",
    "group": "space"
  },
  {
    "name": "space.set_time",
    "signature": "space.set_time(seconds: number)",
    "doc": "Sets the system clock: where every planet is.",
    "group": "space"
  },
  {
    "name": "space.settle",
    "signature": "space.settle()",
    "doc": "Puts everyone with a Routine at the stop the clock says.",
    "group": "space"
  },
  {
    "name": "space.reveal",
    "signature": "space.reveal(body: string)",
    "doc": "Shows a hidden body.",
    "group": "space"
  },
  {
    "name": "space.bodies",
    "signature": "space.bodies()",
    "doc": "Every visible body, one per line: name and parent.",
    "group": "space"
  },
  {
    "name": "space.plan",
    "signature": "space.plan(body: string)",
    "doc": "A route plan to a body: distance, delta-v and the fuel it needs.",
    "group": "space"
  },
  {
    "name": "space.autopilot",
    "signature": "space.autopilot(on: boolean)",
    "doc": "Engages or releases the autopilot toward the target.",
    "group": "space"
  },
  {
    "name": "space.use_reserve",
    "signature": "space.use_reserve()",
    "doc": "Releases the emergency fuel reserve (once, below 35%).",
    "group": "space"
  },
  {
    "name": "space.repair_part",
    "signature": "space.repair_part(part: string, amount: number)",
    "doc": "Repairs (+) or damages (-) engine, rcs, gear or scanner; returns its condition.",
    "group": "space"
  },
  {
    "name": "space.set_wind",
    "signature": "space.set_wind(x: number, y: number, z: number)",
    "doc": "Wind on the ship and walker (m/s, site frame).",
    "group": "space"
  },
  {
    "name": "space.allow_boarding",
    "signature": "space.allow_boarding(allowed: boolean)",
    "doc": "Whether E boards the ship.",
    "group": "space"
  },
  {
    "name": "world.wear",
    "signature": "world.wear(models: string)",
    "doc": "Dresses this script's own character in gear: catalog model ids (space-separated; \"214:#8aa6d6\" tints one) rigged to its skeleton, worn over its body and moving with it. Empty undresses.",
    "group": "world"
  },
  {
    "name": "world.wildlife_state",
    "signature": "world.wildlife_state(name: string)",
    "doc": "0 calm, 1 wary, 2 fleeing, -1 not an animal.",
    "group": "world"
  },
  {
    "name": "hud.announce",
    "signature": "hud.announce(text: string)",
    "doc": "Reads a line aloud for screen readers and shows it briefly.",
    "group": "hud"
  },
  {
    "name": "ui.set_color",
    "signature": "ui.set_color(name: string, color: string)",
    "doc": "A UI element's text colour (#rrggbb); empty restores its own.",
    "group": "ui"
  },
  {
    "name": "hud.cue",
    "signature": "hud.cue(name: string)",
    "doc": "Plays an interface sound cue.",
    "group": "hud"
  },
  {
    "name": "hud.waypoint",
    "signature": "hud.waypoint(id: string, body: string, latitude: number, longitude: number, label: string)",
    "doc": "A waypoint at a place on a planet.",
    "group": "hud"
  },
  {
    "name": "hud.clear_waypoint",
    "signature": "hud.clear_waypoint(id: string)",
    "doc": "Removes a waypoint.",
    "group": "hud"
  },
  {
    "name": "hud.map",
    "signature": "hud.map(mode: string)",
    "doc": "off, system, surface or toggle.",
    "group": "hud"
  },
  {
    "name": "hud.minimap",
    "signature": "hud.minimap(shown: boolean)",
    "doc": "Shows or hides the minimap.",
    "group": "hud"
  },
  {
    "name": "hud.open_settings",
    "signature": "hud.open_settings()",
    "doc": "Opens the player settings panel.",
    "group": "hud"
  },
  {
    "name": "hud.visor",
    "signature": "hud.visor(helmet: boolean, integrity: number, frost: number, heat: number)",
    "doc": "The helmet visor: on or off, integrity 0-1 (cracks below), frost and heat shimmer 0-1.",
    "group": "hud"
  },
  {
    "name": "hud.suit_light",
    "signature": "hud.suit_light(mode: string)",
    "doc": "auto, on or off.",
    "group": "hud"
  },
  {
    "name": "hud.system",
    "signature": "hud.system(title: string, body: string)",
    "doc": "Shows a Ledger system window (title, body lines split by \\n); replaces the open one.",
    "group": "hud"
  },
  {
    "name": "hud.system_close",
    "signature": "hud.system_close()",
    "doc": "Closes the Ledger system window.",
    "group": "hud"
  },
  {
    "name": "hud.panels",
    "signature": "hud.panels(spec: string)",
    "doc": "Plays a comic-panel cutscene: one shot per line, \"x y z > tx ty tz | caption | sfx | seconds\". Space or Enter skips.",
    "group": "hud"
  },
  {
    "name": "hud.boss",
    "signature": "hud.boss(name: string, title: string)",
    "doc": "A boss bar (health and stagger) for the named entity; an empty name hides it.",
    "group": "hud"
  },
  {
    "name": "audio.music",
    "signature": "audio.music(mood: string)",
    "doc": "off, title, explore, night, flight, space, signal or tension.",
    "group": "audio"
  },
  {
    "name": "audio.ambience",
    "signature": "audio.ambience(layer: string, level: number)",
    "doc": "An ambience layer's level 0-1: wind, rain, settlement, wildlife or signal.",
    "group": "audio"
  },
  {
    "name": "fx.weather",
    "signature": "fx.weather(rain: number, fog: number, wind_x: number, wind_z: number)",
    "doc": "Weather: rain and fog 0-1, wind in m/s.",
    "group": "fx"
  },
  {
    "name": "fx.light",
    "signature": "fx.light(ambient: number, sun: number)",
    "doc": "Sets the ambient and sun intensities over the Environment's (a lit street vs a dark dungeon in one scene).",
    "group": "fx"
  },
  {
    "name": "fx.dust",
    "signature": "fx.dust(color: string, density: number)",
    "doc": "Dust kicked up on landing: a #rrggbb colour and 0-1 density.",
    "group": "fx"
  },
  {
    "name": "fx.soft_ground",
    "signature": "fx.soft_ground(soft: boolean)",
    "doc": "Whether footprints show.",
    "group": "fx"
  },
  {
    "name": "scanner.tune",
    "signature": "scanner.tune(range: number, time: number, condition: number)",
    "doc": "Scanner range, scan time and condition multipliers.",
    "group": "scanner"
  },
  {
    "name": "scanner.sky_key",
    "signature": "scanner.sky_key(key: string)",
    "doc": "What scanning the sky identifies.",
    "group": "scanner"
  },
  {
    "name": "scanner.catalogued",
    "signature": "scanner.catalogued(id: string)",
    "doc": "Marks a scan id as already known.",
    "group": "scanner"
  },
  {
    "name": "scanner.prospect",
    "signature": "scanner.prospect(label: string, range: number, keys: string)",
    "doc": "Highlights scatter of these species keys (comma-separated); empty label stops.",
    "group": "scanner"
  }
];
