// Generated from the Aether asset kit (CC0 1.0; see assets/CREDITS.md). Regenerate by
// re-running the script recorded in docs/IMPLEMENTATION_STATUS.md if the kit changes.
export interface CatalogEntry {
  id: number;
  category: string;
  name: string;
  path: string;
  // True for a rigged, animated model (SkeletonUtils.clone required; has AnimationClips).
  animated?: boolean;
}

export const modelCatalog: CatalogEntry[] = [
  { id: 2, category: "buildings", name: "Apartment 1", path: "./kit/buildings/apartment-1.glb" },
  { id: 3, category: "buildings", name: "Apartment 2", path: "./kit/buildings/apartment-2.glb" },
  { id: 4, category: "buildings", name: "Apartment 3", path: "./kit/buildings/apartment-3.glb" },
  { id: 5, category: "buildings", name: "House 1", path: "./kit/buildings/house-1.glb" },
  { id: 6, category: "buildings", name: "House 2", path: "./kit/buildings/house-2.glb" },
  { id: 7, category: "buildings", name: "House 3", path: "./kit/buildings/house-3.glb" },
  { id: 8, category: "buildings", name: "Office 1", path: "./kit/buildings/office-1.glb" },
  { id: 9, category: "buildings", name: "Office 2", path: "./kit/buildings/office-2.glb" },
  { id: 10, category: "buildings", name: "Office 3", path: "./kit/buildings/office-3.glb" },
  { id: 11, category: "buildings", name: "Parking 1", path: "./kit/buildings/parking-1.glb" },
  { id: 12, category: "buildings", name: "Parking 2", path: "./kit/buildings/parking-2.glb" },
  { id: 13, category: "buildings", name: "Parking 3", path: "./kit/buildings/parking-3.glb" },
  { id: 14, category: "buildings", name: "Retail 1", path: "./kit/buildings/retail-1.glb" },
  { id: 15, category: "buildings", name: "Retail 2", path: "./kit/buildings/retail-2.glb" },
  { id: 16, category: "buildings", name: "Retail 3", path: "./kit/buildings/retail-3.glb" },
  { id: 17, category: "buildings", name: "Shophouse 1", path: "./kit/buildings/shophouse-1.glb" },
  { id: 18, category: "buildings", name: "Shophouse 2", path: "./kit/buildings/shophouse-2.glb" },
  { id: 19, category: "buildings", name: "Shophouse 3", path: "./kit/buildings/shophouse-3.glb" },
  { id: 20, category: "buildings", name: "Tower 1", path: "./kit/buildings/tower-1.glb" },
  { id: 21, category: "buildings", name: "Tower 2", path: "./kit/buildings/tower-2.glb" },
  { id: 22, category: "buildings", name: "Tower 3", path: "./kit/buildings/tower-3.glb" },
  { id: 23, category: "buildings", name: "Warehouse 1", path: "./kit/buildings/warehouse-1.glb" },
  { id: 24, category: "buildings", name: "Warehouse 2", path: "./kit/buildings/warehouse-2.glb" },
  { id: 25, category: "buildings", name: "Warehouse 3", path: "./kit/buildings/warehouse-3.glb" },
  { id: 26, category: "furniture", name: "Barrier", path: "./kit/furniture/barrier.glb" },
  { id: 27, category: "furniture", name: "Bin", path: "./kit/furniture/bin.glb" },
  { id: 28, category: "furniture", name: "Bollard", path: "./kit/furniture/bollard.glb" },
  { id: 29, category: "furniture", name: "Busstop", path: "./kit/furniture/busstop.glb" },
  { id: 30, category: "furniture", name: "Cone", path: "./kit/furniture/cone.glb" },
  { id: 31, category: "furniture", name: "Guardrail", path: "./kit/furniture/guardrail.glb" },
  { id: 32, category: "furniture", name: "Hydrant", path: "./kit/furniture/hydrant.glb" },
  { id: 33, category: "furniture", name: "Manhole", path: "./kit/furniture/manhole.glb" },
  { id: 34, category: "furniture", name: "Streetlamp Double", path: "./kit/furniture/streetlamp-double.glb" },
  { id: 35, category: "furniture", name: "Streetlamp", path: "./kit/furniture/streetlamp.glb" },
  { id: 36, category: "furniture", name: "Utilitypole", path: "./kit/furniture/utilitypole.glb" },
  { id: 37, category: "nature", name: "Bush 1", path: "./kit/nature/bush-1.glb" },
  { id: 38, category: "nature", name: "Bush 2", path: "./kit/nature/bush-2.glb" },
  { id: 39, category: "nature", name: "Fence Chainlink", path: "./kit/nature/fence-chainlink.glb" },
  { id: 40, category: "nature", name: "Fence Picket", path: "./kit/nature/fence-picket.glb" },
  { id: 41, category: "nature", name: "Planter", path: "./kit/nature/planter.glb" },
  { id: 42, category: "nature", name: "Rock Large", path: "./kit/nature/rock-large.glb" },
  { id: 43, category: "nature", name: "Rock Medium", path: "./kit/nature/rock-medium.glb" },
  { id: 44, category: "nature", name: "Rock Small", path: "./kit/nature/rock-small.glb" },
  { id: 45, category: "nature", name: "Tree Banana", path: "./kit/nature/tree-banana.glb" },
  { id: 46, category: "nature", name: "Tree Broadleaf 1", path: "./kit/nature/tree-broadleaf-1.glb" },
  { id: 47, category: "nature", name: "Tree Broadleaf 2", path: "./kit/nature/tree-broadleaf-2.glb" },
  { id: 48, category: "nature", name: "Tree Broadleaf 3", path: "./kit/nature/tree-broadleaf-3.glb" },
  { id: 49, category: "nature", name: "Tree Conifer 1", path: "./kit/nature/tree-conifer-1.glb" },
  { id: 50, category: "nature", name: "Tree Conifer 2", path: "./kit/nature/tree-conifer-2.glb" },
  { id: 51, category: "nature", name: "Tree Palm 1", path: "./kit/nature/tree-palm-1.glb" },
  { id: 52, category: "nature", name: "Tree Palm 2", path: "./kit/nature/tree-palm-2.glb" },
  { id: 53, category: "nature", name: "Tree Palm 3", path: "./kit/nature/tree-palm-3.glb" },
  { id: 54, category: "roads", name: "Road Bend", path: "./kit/roads/road-bend.glb" },
  { id: 55, category: "roads", name: "Road Bridge", path: "./kit/roads/road-bridge.glb" },
  { id: 56, category: "roads", name: "Road Cross Crossing", path: "./kit/roads/road-cross-crossing.glb" },
  { id: 57, category: "roads", name: "Road Cross", path: "./kit/roads/road-cross.glb" },
  { id: 58, category: "roads", name: "Road End", path: "./kit/roads/road-end.glb" },
  { id: 59, category: "roads", name: "Road Ramp", path: "./kit/roads/road-ramp.glb" },
  { id: 60, category: "roads", name: "Road Roundabout", path: "./kit/roads/road-roundabout.glb" },
  { id: 61, category: "roads", name: "Road Straight Arrows", path: "./kit/roads/road-straight-arrows.glb" },
  { id: 62, category: "roads", name: "Road Straight Crossing", path: "./kit/roads/road-straight-crossing.glb" },
  { id: 63, category: "roads", name: "Road Straight Solid", path: "./kit/roads/road-straight-solid.glb" },
  { id: 64, category: "roads", name: "Road Straight", path: "./kit/roads/road-straight.glb" },
  { id: 65, category: "roads", name: "Road T Crossing", path: "./kit/roads/road-t-crossing.glb" },
  { id: 66, category: "roads", name: "Road T", path: "./kit/roads/road-t.glb" },
  { id: 67, category: "signs", name: "Sign Crossing", path: "./kit/signs/sign-crossing.glb" },
  { id: 68, category: "signs", name: "Sign Guide", path: "./kit/signs/sign-guide.glb" },
  { id: 69, category: "signs", name: "Sign Keepleft", path: "./kit/signs/sign-keepleft.glb" },
  { id: 70, category: "signs", name: "Sign Keepright", path: "./kit/signs/sign-keepright.glb" },
  { id: 71, category: "signs", name: "Sign Noentry", path: "./kit/signs/sign-noentry.glb" },
  { id: 72, category: "signs", name: "Sign Noparking", path: "./kit/signs/sign-noparking.glb" },
  { id: 73, category: "signs", name: "Sign Oneway", path: "./kit/signs/sign-oneway.glb" },
  { id: 74, category: "signs", name: "Sign Parking", path: "./kit/signs/sign-parking.glb" },
  { id: 75, category: "signs", name: "Sign Pedestrian", path: "./kit/signs/sign-pedestrian.glb" },
  { id: 76, category: "signs", name: "Sign Roundabout", path: "./kit/signs/sign-roundabout.glb" },
  { id: 77, category: "signs", name: "Sign Route", path: "./kit/signs/sign-route.glb" },
  { id: 78, category: "signs", name: "Sign School", path: "./kit/signs/sign-school.glb" },
  { id: 79, category: "signs", name: "Sign Speed 20", path: "./kit/signs/sign-speed-20.glb" },
  { id: 80, category: "signs", name: "Sign Speed 30", path: "./kit/signs/sign-speed-30.glb" },
  { id: 81, category: "signs", name: "Sign Speed 40", path: "./kit/signs/sign-speed-40.glb" },
  { id: 82, category: "signs", name: "Sign Speed 50", path: "./kit/signs/sign-speed-50.glb" },
  { id: 83, category: "signs", name: "Sign Speed 60", path: "./kit/signs/sign-speed-60.glb" },
  { id: 84, category: "signs", name: "Sign Speed 80", path: "./kit/signs/sign-speed-80.glb" },
  { id: 85, category: "signs", name: "Sign Stop", path: "./kit/signs/sign-stop.glb" },
  { id: 86, category: "signs", name: "Sign Warning", path: "./kit/signs/sign-warning.glb" },
  { id: 87, category: "signs", name: "Sign Yield", path: "./kit/signs/sign-yield.glb" },
  { id: 88, category: "signs", name: "Signal Mast", path: "./kit/signs/signal-mast.glb" },
  { id: 89, category: "signs", name: "Signal Pedestrian", path: "./kit/signs/signal-pedestrian.glb" },
  { id: 90, category: "signs", name: "Signal Post", path: "./kit/signs/signal-post.glb" },
  { id: 91, category: "vehicles", name: "Ambulance", path: "./kit/vehicles/ambulance.glb" },
  { id: 92, category: "vehicles", name: "Boxtruck", path: "./kit/vehicles/boxtruck.glb" },
  { id: 93, category: "vehicles", name: "Bus", path: "./kit/vehicles/bus.glb" },
  { id: 94, category: "vehicles", name: "Hatchback", path: "./kit/vehicles/hatchback.glb" },
  { id: 95, category: "vehicles", name: "Minibus", path: "./kit/vehicles/minibus.glb" },
  { id: 96, category: "vehicles", name: "Pickup", path: "./kit/vehicles/pickup.glb" },
  { id: 97, category: "vehicles", name: "Police", path: "./kit/vehicles/police.glb" },
  { id: 98, category: "vehicles", name: "Sedan", path: "./kit/vehicles/sedan.glb" },
  { id: 99, category: "vehicles", name: "Semi Trailer", path: "./kit/vehicles/semi-trailer.glb" },
  { id: 100, category: "vehicles", name: "Semi", path: "./kit/vehicles/semi.glb" },
  { id: 101, category: "vehicles", name: "Sports", path: "./kit/vehicles/sports.glb" },
  { id: 102, category: "vehicles", name: "Suv", path: "./kit/vehicles/suv.glb" },
  { id: 103, category: "vehicles", name: "Taxi", path: "./kit/vehicles/taxi.glb" },
  { id: 104, category: "vehicles", name: "Van", path: "./kit/vehicles/van.glb" },
  { id: 105, category: "animals", name: "Cat", path: "./kit/animals/cat.glb", animated: true },
  { id: 106, category: "animals", name: "Chicken", path: "./kit/animals/chicken.glb", animated: true },
  { id: 107, category: "animals", name: "Cow", path: "./kit/animals/cow.glb", animated: true },
  { id: 108, category: "animals", name: "Crow", path: "./kit/animals/crow.glb", animated: true },
  { id: 109, category: "animals", name: "Deer", path: "./kit/animals/deer.glb", animated: true },
  { id: 110, category: "animals", name: "Dog", path: "./kit/animals/dog.glb", animated: true },
  { id: 111, category: "animals", name: "Donkey", path: "./kit/animals/donkey.glb", animated: true },
  { id: 112, category: "animals", name: "Fox", path: "./kit/animals/fox.glb", animated: true },
  { id: 113, category: "animals", name: "Goat", path: "./kit/animals/goat.glb", animated: true },
  { id: 114, category: "animals", name: "Gull", path: "./kit/animals/gull.glb", animated: true },
  { id: 115, category: "animals", name: "Horse", path: "./kit/animals/horse.glb", animated: true },
  { id: 116, category: "animals", name: "Pig", path: "./kit/animals/pig.glb", animated: true },
  { id: 117, category: "animals", name: "Pigeon", path: "./kit/animals/pigeon.glb", animated: true },
  { id: 118, category: "animals", name: "Sheep", path: "./kit/animals/sheep.glb", animated: true },
  { id: 119, category: "people", name: "Hero", path: "./kit/people/hero.glb", animated: true },
  { id: 120, category: "people", name: "Npc Casual 1", path: "./kit/people/npc-casual-1.glb", animated: true },
  { id: 121, category: "people", name: "Npc Casual 2", path: "./kit/people/npc-casual-2.glb", animated: true },
  { id: 122, category: "people", name: "Npc Dress", path: "./kit/people/npc-dress.glb", animated: true },
  { id: 123, category: "people", name: "Npc Elder", path: "./kit/people/npc-elder.glb", animated: true },
  { id: 124, category: "people", name: "Npc Hoodie", path: "./kit/people/npc-hoodie.glb", animated: true },
  { id: 125, category: "people", name: "Npc Office F", path: "./kit/people/npc-office-f.glb", animated: true },
  { id: 126, category: "people", name: "Npc Office M", path: "./kit/people/npc-office-m.glb", animated: true },
  { id: 127, category: "people", name: "Npc Sport", path: "./kit/people/npc-sport.glb", animated: true },
  { id: 128, category: "people", name: "Npc Teen", path: "./kit/people/npc-teen.glb", animated: true },
  { id: 129, category: "people", name: "Npc Uniform", path: "./kit/people/npc-uniform.glb", animated: true },
  { id: 130, category: "people", name: "Npc Vendor", path: "./kit/people/npc-vendor.glb", animated: true },
  { id: 131, category: "people", name: "Npc Worker", path: "./kit/people/npc-worker.glb", animated: true },
];

export const catalogCategories = Array.from(
  new Set(modelCatalog.map((e) => e.category)),
);
