// Writes bridge_fields.hpp and bridgeFields.ts from tools/bridge/fields.mjs.
// `--check` fails (exit 1) if either file is out of date.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { spaceFields, entityFields, fighterFields, meleeEventFields } from "./fields.mjs";

const root = fileURLToPath(new URL("../../", import.meta.url));
const snake = (name) => name.replace(/[A-Z]/g, (c) => "_" + c.toLowerCase());
const header = "// Generated by tools/bridge/gen_fields.mjs from tools/bridge/fields.mjs. Don't edit.\n";

const cpp = (enumName, fields) =>
  `enum class ${enumName} : int {\n${fields.map(([name, n, doc]) => `    ${snake(name)} = ${n},${doc ? ` // ${doc}` : ""}`).join("\n")}\n};\n`;
const ts = (constName, fields) =>
  `export const ${constName} = {\n${fields.map(([name, n, doc]) => `${doc ? `  // ${doc}\n` : ""}  ${name}: ${n},`).join("\n")}\n} as const;\n`;

const outputs = {
  "apps/editor/runtime/bridge_fields.hpp": `${header}#pragma once\n\n${cpp("SpaceField", spaceFields)}\n${cpp("EntityField", entityFields)}\n${cpp("FighterField", fighterFields)}\n${cpp("MeleeEventField", meleeEventFields)}`,
  "apps/editor/src/editor/bridgeFields.ts": `${header}\n// editor_space_value(field)\n${ts("SpaceField", spaceFields)}\n// editor_value(index, field)\n${ts("EntityField", entityFields)}\n// editor_fighter_value(index, field)\n${ts("FighterField", fighterFields)}\n// editor_melee_event(index, field)\n${ts("MeleeEventField", meleeEventFields)}`,
};
let stale = false;
for (const [path, text] of Object.entries(outputs)) {
  const full = root + path;
  let current = "";
  try {
    current = readFileSync(full, "utf8");
  } catch {}
  if (current === text) continue;
  if (process.argv.includes("--check")) {
    console.error(`${path} is out of date: run node tools/bridge/gen_fields.mjs`);
    stale = true;
  } else {
    writeFileSync(full, text);
    console.log(`wrote ${path}`);
  }
}
process.exit(stale ? 1 : 0);
