// Writes apps/editor/src/editor/runtimeExports.ts (0.77.0): the TypeScript
// type of every EXPORT function in apps/editor/runtime/bridge*.cpp, read from
// the C++ signatures themselves, so the editor can't call a function that
// doesn't exist or pass the wrong number of arguments. Functions taking or
// returning strings go through ccall and are listed by name. `--check` fails
// when the file is out of date.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../", import.meta.url));
const runtimeDir = root + "apps/editor/runtime/";
const source = readdirSync(runtimeDir)
  .filter((f) => /^bridge.*\.cpp$/.test(f))
  .sort()
  .map((f) => readFileSync(runtimeDir + f, "utf8"))
  .join("\n");
const exports = [];
for (const match of source.matchAll(/^EXPORT\s+([\w\s*:]+?)\s*\b(editor_\w+)\s*\(([^)]*)\)\s*\{/gm)) {
  const [, ret, name, params] = match;
  const args = params
    .split(",")
    .map((p) => p.trim())
    .filter((p) => p && p !== "void")
    .map((p) => {
      const parts = p.split(/\s+/);
      const argName = parts.pop().replace(/^\*+/, "");
      return { name: argName, string: /char\s*\*|char\*/.test(p) };
    });
  exports.push({ name, ret: ret.replace(/\s+/g, " ").trim(), args });
}
const camel = (s) => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
const tsReturn = (ret) => (ret === "void" ? "void" : /char/.test(ret) ? "string" : "number");
const numeric = exports.filter((e) => !/char/.test(e.ret) && !e.args.some((a) => a.string));
const viaCcall = exports.filter((e) => /char/.test(e.ret) || e.args.some((a) => a.string));
const text = `// Generated by tools/bridge/gen_exports.mjs from apps/editor/runtime/bridge*.cpp. Don't edit.
// ${exports.length} exports: ${numeric.length} called directly, ${viaCcall.length} through ccall (they take or return strings).

export interface RuntimeExports {
${numeric.map((e) => `  _${e.name}(${e.args.map((a) => `${camel(a.name)}: number`).join(", ")}): ${tsReturn(e.ret)};`).join("\n")}
}

// Called with runtime.ccall(name, ...) because a string crosses the boundary.
export const ccallExports = {
${viaCcall.map((e) => `  ${e.name}: { returns: "${tsReturn(e.ret)}", args: [${e.args.map((a) => `"${a.string ? "string" : "number"}"`).join(", ")}] },`).join("\n")}
} as const;
export type CcallExport = keyof typeof ccallExports;
`;
const out = root + "apps/editor/src/editor/runtimeExports.ts";
let current = "";
try {
  current = readFileSync(out, "utf8");
} catch {}
if (current !== text) {
  if (process.argv.includes("--check")) {
    console.error("apps/editor/src/editor/runtimeExports.ts is out of date: run node tools/bridge/gen_exports.mjs");
    process.exit(1);
  }
  writeFileSync(out, text);
  console.log(`wrote runtimeExports.ts (${exports.length} exports)`);
}
