// Generated by tools/script_api/gen.mjs from tools/script_api/api.mjs. Don't edit.
// The named scripting helpers (0.77.0), run after the core prelude.
#pragma once

namespace engine::script {
inline constexpr const char *api_prelude = R"lua(
-- Generated by tools/script_api/gen.mjs from tools/script_api/api.mjs. Don't edit.
hud = hud or {}
audio = audio or {}
fx = fx or {}
scanner = scanner or {}
function space.set_hull(value) return space.call("hull", "", value) end
function space.set_time(seconds) return space.call("time", "", seconds) end
function space.settle() return space.call("settle") end
function space.reveal(body) return space.call("reveal", body) end
function space.bodies() local r = space.call("bodies") return r and r.text or "" end
function space.plan(body) local r = space.call("plan", body) if not r then return nil end return {distance = r[1], closing_speed = r[2], delta_v = r[3], fuel = r[4], status = r[5]} end
function space.autopilot(on) return space.call("autopilot", "", on and 1 or 0) end
function space.use_reserve() return space.call("reserve") end
function space.repair_part(part, amount) local r = space.call("part", part, amount) return r and r[1] end
function space.set_wind(x, y, z) return space.call("wind", "", x, y, z) end
function space.allow_boarding(allowed) return space.call("board_key", "", allowed and 1 or 0) end
function world.wear(models) host.send("outfit", models or "") end
function world.wildlife_state(name) local r = space.call("wildlife", name) return r and r[1] or -1 end
function hud.announce(text) host.send("announce", text) end
function ui.set_color(name, color) host.send("ui_color", name .. "|" .. (color or "")) end
function hud.cue(name) host.send("cue", name) end
function hud.waypoint(id, body, latitude, longitude, label) host.send("waypoint", table.concat({id, body, latitude, longitude, label or ""}, "|")) end
function hud.clear_waypoint(id) host.send("waypoint_clear", id) end
function hud.map(mode) host.send("map", mode) end
function hud.minimap(shown) host.send("minimap", shown and "1" or "0") end
function hud.open_settings() host.send("settings", "") end
function hud.visor(helmet, integrity, frost, heat) host.send("visor", string.format("%d %.2f %.2f %.2f", helmet and 1 or 0, integrity, frost, heat)) end
function hud.suit_light(mode) host.send("suitlight", mode) end
function hud.system(title, body) host.send("system", title .. "|" .. (body or "")) end
function hud.system_close() host.send("system", "") end
function hud.panels(spec) host.send("panels", spec) end
function hud.boss(name, title) host.send("boss", (name or "") .. "|" .. (title or "")) end
function audio.music(mood) host.send("music", mood) end
function audio.ambience(layer, level) host.send("audio", string.format("%s %.2f", layer, level)) end
function fx.weather(rain, fog, wind_x, wind_z) host.send("weather", string.format("%.2f %.2f %.1f %.1f", rain, fog, wind_x, wind_z)) end
function fx.light(ambient, sun) host.send("light", string.format("%.3f %.3f", ambient, sun)) end
function fx.dust(color, density) host.send("dust", color .. " " .. density) end
function fx.soft_ground(soft) host.send("soft", soft and "1" or "0") end
function scanner.tune(range, time, condition) host.send("scanner", range .. " " .. time .. " " .. condition) end
function scanner.sky_key(key) host.send("sky_scan", key) end
function scanner.catalogued(id) host.send("catalogued", id) end
function scanner.prospect(label, range, keys) host.send("prospect", label .. "|" .. range .. "|" .. keys) end
)lua";
} // namespace engine::script
